### ISSUE TITLE
Many select calls when using relationships in model __str__

### ISSUE THREAD

**Issue by MaxDude132** [FactoryBoy/factory_boy#1009]
#### The problem
When the model's `__str__` uses relations, the factory runs SELECT many times. This is because of `builer.py:357`, where it raises an error if a parameter is not found on the model. The issue is that this affects the factory Traits, so it calls the `__str__` super often for a factory that has many of those. And if a relation is used in the `__str__`, then it makes a huge number of calls because of this, which feels like an oversight.

#### Proposed solution
I believe this could be fixed by simple moving the error message one step higher, in `BuildStep.resolve`. At that higher level, we have all the details necessary to build the error message. In most cases, this error is catched and not propagated, so actually building the message every time is pretty costly.

For this though, we would likely need a new Error, which would allow us to only delay this particular error. I believe something like ParameterMissingError would be a good descriptive name that would have the nice advantage of adding the possibility for users to handle the case in `_generate` if needed.

#### Extra notes
In our project, this causes hundreds of calls to the database for each Factory instantiated, because we make extensive use of Traits. We have separate models for dynamic translations, and we like using those in the `__str__` because it makes it much cleaner in Django Admin. 

Let me know if you want me to start a PR for this.

**Comment by francoisfreitag** [comment]
The message seems to use the `__repr__`, but I guess it can easily turn into calling `__str__` on your models.
https://github.com/FactoryBoy/factory_boy/blob/9b256e48dd58ef7c97e3ddf09d972d1bb1d2df8e/factory/builder.py#L391-L393

I’m unclear where the `AttributeError` is caught, and how moving the error message building to `resolve` would fix the issue. But if you can open a PR with a test case to better describe the problem, I’ll happily take a look at it. If it does improve the state of the library, I see no reason to reject it.

**Comment by rbarrois** [comment]
Looking into this, the only situation I see where this could occur is if your factories use lots of `factory.SelfAttribute("foo.bar.baz", default="X")`, and `.baz` is not provided.

On the base point, it is quite dangerous to follow relationships in a model's `__repr__` or `__str__` implementations, as that would cause unexpected queries — which might error out if the transaction failed earlier.

I would need to see some actual example code in order to move forward on this issue; please feel free to reopen this issue if you have some more details.

**Comment by baldurh** [comment]
@rbarrois the `AttributeError` is actually raised whenever you pass a Trait parameter to the factory. So it can happen quite a lot.

**Comment by baldurh** [comment]
I believe I’ve narrowed down the issue. It seems to be related to when `Trait` params are **declared** and **not used** in `DjangoModelFactory` classes for models with related fields. I was able to reproduce this by using either `RelatedFactory` or `SubFactory`. See the examples below.

(I wrote this in my current project and didn’t have time to create a repro repo. I assume you can easily set up something similar in your environment)

<details><summary>Test Code using RelatedFactory</summary>

```python
import factory
import factory.fuzzy
import pytest

from app.models import Markdown, MarkdownType

# Classes are defined as such: 

# class MarkdownType(models.Model):
#     slug = models.CharField(max_length=100, unique=True)
#     title = models.CharField(max_length=100)

#     def __str__(self):
#         print("MarkdownType.__str__ called")
#         return self.title


# class Markdown(models.Model):
#     text = models.TextField()
#     version = models.IntegerField()
#     markdown_type = models.ForeignKey(MarkdownType, on_delete=models.PROTECT)
#     time_created = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         print("Markdown.__str__ called")
#         return str(self.id)


class MarkdownFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Markdown

    text = factory.fuzzy.FuzzyText(length=10)
    version = 1

    # Just declaring Trait params causes MarkdownType.__str__ to be called
    # when initialising MarkdownFactory without using it
    class Params:
        is_test = factory.Trait(text="test")

        # Declaring more Trait params will cause MarkdownType.__str__
        # to be called more times. Basically it’s called for each unused
        # Trait param

        # is_foo = factory.Trait(text="foo")


class MarkdownTypeFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = MarkdownType

    slug = factory.fuzzy.FuzzyText(length=10)
    title = factory.fuzzy.FuzzyText(length=10)

    markdown = factory.RelatedFactory(
        MarkdownFactory, factory_related_name="markdown_type"
    )


@pytest.mark.django_db
def test_markdown():
    print("1")
    # MarkdownType.__str__ will *NOT* be called
    markdown_type_1 = MarkdownTypeFactory(markdown=None)
    markdown_type_2 = MarkdownTypeFactory(markdown=None)
    print("2")
    # MarkdownType.__str__ *WILL* be called
    MarkdownFactory(markdown_type=markdown_type_1)
    print("3")
    # MarkdownType.__str__ will *NOT* be called (unless more Trait params are added)
    MarkdownFactory(is_test=True, markdown_type=markdown_type_2)
    print("4")
    # MarkdownType.__str__ *WILL* be called
    MarkdownTypeFactory()

``` 
</details> 

Running the test above using `pytest trait_test.py -s` will output:
```
1
2
MarkdownType.__str__ called
3
4
MarkdownType.__str__ called
```

The exception is raised here: https://github.com/FactoryBoy/factory_boy/blob/master/factory/builder.py#L370 which calls https://github.com/FactoryBoy/factory_boy/blob/master/factory/builder.py#L134 which causes the `__repr__` method and then `__str__` method of a related model instance to be called.

Stacktrace for a breakpoint in `MarkdownType.__str__`

<details><summary>Stacktrace</summary>

```
  [26] /code_path/app_path/trait_test.py(69)test_markdown()
       MarkdownFactory(markdown_type=markdown_type_1)
  [27] /code_path/.venv/lib/python3.11/site-packages/factory/base.py(40)__call__()
       return cls.create(**kwargs)
  [28] /code_path/.venv/lib/python3.11/site-packages/factory/base.py(528)create()
       return cls._generate(enums.CREATE_STRATEGY, kwargs)
  [29] /code_path/.venv/lib/python3.11/site-packages/factory/django.py(117)_generate()
       return super()._generate(strategy, params)
  [30] /code_path/.venv/lib/python3.11/site-packages/factory/base.py(465)_generate()
       return step.build()
  [31] /code_path/.venv/lib/python3.11/site-packages/factory/builder.py(258)build()
       step.resolve(pre)
  [32] /code_path/.venv/lib/python3.11/site-packages/factory/builder.py(199)resolve()
       self.attributes[field_name] = getattr(self.stub, field_name)
  [33] /code_path/.venv/lib/python3.11/site-packages/factory/builder.py(344)__getattr__()
       value = value.evaluate_pre(
  [34] /code_path/.venv/lib/python3.11/site-packages/factory/declarations.py(477)evaluate_pre()
       choice = self.decider.evaluate(instance=instance, step=step, extra={})
  [35] /code_path/.venv/lib/python3.11/site-packages/factory/declarations.py(166)evaluate()
       return deepgetattr(target, self.attribute_name, self.default)
  [36] /code_path/.venv/lib/python3.11/site-packages/factory/declarations.py(128)deepgetattr()
       return getattr(obj, name)
  [37] /code_path/.venv/lib/python3.11/site-packages/factory/builder.py(358)__getattr__()
       "definitions are %r." % (name, self.__values, self.__declarations))
  [38] /code_path/.venv/lib/python3.11/site-packages/factory/builder.py(134)__repr__()
       return '<DeclarationSet: %r>' % self.as_dict()
  [39] /code_path/.venv/lib/python3.11/site-packages/django/db/models/base.py(588)__repr__()
       return "<%s: %s>" % (self.__class__.__name__, self)
> [40] /code_path/app_path/agreements/models.py(33)__str__()
       print("MarkdownType.__str__ called")
```
</details>


Uncommenting the `is_foo` Trait param will change the output to:
```
1
2
MarkdownType.__str__ called // <-- once for is_test
MarkdownType.__str__ called // <-- once for is_foo
3
MarkdownType.__str__ called // <-- once for is_foo
4
MarkdownType.__str__ called // <-- once for is_test
MarkdownType.__str__ called // <-- once for is_foo
```

<details><summary>Test Code using SubFactory</summary>

```python
import factory
import factory.fuzzy
import pytest

from app.models import Markdown, MarkdownType

# class MarkdownType(models.Model):
#     slug = models.CharField(max_length=100, unique=True)
#     title = models.CharField(max_length=100)

#     def __str__(self):
#         print("MarkdownType.__str__ called")
#         return self.title


# class Markdown(models.Model):
#     text = models.TextField()
#     version = models.IntegerField()
#     markdown_type = models.ForeignKey(MarkdownType, on_delete=models.PROTECT)
#     time_created = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         print("Markdown.__str__ called")
#         return str(self.id)


class MarkdownTypeFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = MarkdownType

    slug = factory.fuzzy.FuzzyText(length=10)
    title = factory.fuzzy.FuzzyText(length=10)


class MarkdownFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Markdown

    text = factory.fuzzy.FuzzyText(length=10)
    version = 1

    markdown_type = factory.SubFactory(MarkdownTypeFactory)

    class Params:
        is_test = factory.Trait(text="test")


@pytest.mark.django_db
def test_markdown():
    print("1")
    # MarkdownType.__str__ will *NOT* be called
    markdown_type = MarkdownTypeFactory()
    print("2")
    # MarkdownType.__str__ *WILL* be called
    MarkdownFactory(markdown_type=markdown_type)
```
</details> 

Running the second setup will output:

```
1
2
MarkdownType.__str__ called
```

**Comment by baldurh** [comment]
> I’m unclear where the `AttributeError` is caught, and how moving the error message building to `resolve` would fix the issue. 

@francoisfreitag it’s caught in `deepgetattr` in `declarations.py` and there it checks for a default value and returns it if it exists. 

https://github.com/FactoryBoy/factory_boy/blob/68feb45e182f9acccfde671b7ba0babb5bc7ce11/factory/declarations.py#L191-L195

I’m curious to know in which cases the detailed exception message is actually useful to anyone?

I suggest the error message is changed from:
```python
raise AttributeError(
    "The parameter %r is unknown. Evaluated attributes are %r, "
    "definitions are %r." % (name, self.__values, self.__declarations))
```
to:
```python
raise AttributeError(
    "The parameter %r is unknown. "
    "Definitions are %r." % (name, list(self.__declarations))
)
```

Then for this factory:
```python
class FieldFactory(factory.Factory):
    name = factory.fuzzy.FuzzyText(length=5)
    value = factory.fuzzy.FuzzyText(length=5)
    bar = factory.SelfAttribute("foo")
```

The error message goes from:

`AttributeError: The parameter 'foo' is unknown. Evaluated attributes are {'name': 'PwkIJ', 'value': 'hcfJd'}, Definitions are <DeclarationSet: {'name': <factory.fuzzy.FuzzyText object at 0x13a34aa90>, 'value': <factory.fuzzy.FuzzyText object at 0x13a34b190>, 'bar': <SelfAttribute('foo', default=<class 'factory.declarations._UNSPECIFIED'>)>}>.`

to:

`AttributeError: The parameter 'foo' is unknown. Definitions are ['name', 'value', 'bar'].`

Which is way more readable and useful. I don’t see any reason to include the detailed declarations and all the values already evaluated in the factory.
