### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by uri-rodberg** [FactoryBoy/factory_boy#1011]
1. No ChangeLog for version 3.2.1 (released on October 26, 2021)
2. I see there are commits from October 2022 that hasn't been released to PyPI yet. Are you going to release a new version to PyPI?

**Comment by francoisfreitag** [comment]
Hi Uri,

1. That’s right. I’m not sure when that will be fixed, in the meantime, can use GitHub compare feature: https://github.com/FactoryBoy/factory_boy/compare/3.2.0...3.2.1
2. https://github.com/FactoryBoy/factory_boy/issues/886 blocks the release. Feel free to read though the issue and suggested patch, and provide feedback!

**Comment by uri-rodberg** [comment]
> Hi Uri,
> 
> 1. That’s right. I’m not sure when that will be fixed, in the meantime, can use GitHub compare feature: [3.2.0...3.2.1](https://github.com/FactoryBoy/factory_boy/compare/3.2.0...3.2.1)


It looks like there had been a changelog for 3.2.1 which has been deleted. Maybe revert the delete?

https://github.com/FactoryBoy/factory_boy/blob/88458348b01c347e31cf1524a71482923d406a4f/docs/changelog.rst

**Comment by francoisfreitag** [comment]
That change never reached the master branch. Probably a missing merge.
I’ll open a PR to add it back. Thanks!

**Comment by francoisfreitag** [comment]
https://github.com/FactoryBoy/factory_boy/pull/1012

**Comment by rbarrois** [comment]
Done! :)
