### ISSUE TITLE
RelatedFactory confusion

### ISSUE THREAD

**Issue by dimitri-b** [FactoryBoy/factory_boy#1018]
Hi,
The example code from the RelatedFactory reference page suggests that the object defined by the RelatedFactory will be generated and can be accessed via a mysterious `City.objects` attribute.

https://factoryboy.readthedocs.io/en/latest/reference.html#relatedfactory

I made all sorts of attempts to find the objects generated by the RelatedFactory declaration in the example but couldn't find any. `City.objects` attribute doesn't exist. I assume there is some extra setup code missing in addition to the model class declarations.

I understand that the RelatedFactory objects will be created after the 'parent' objects are created, but how the 'related' object can be accessed?
Or did I misunderstand the whole thing?

Thank you for any assistance.

**Comment by francoisfreitag** [comment]
The example is related to the Django ORM, where City refers to a Model (table in database), and objects is what Django calls the default manager, allowing you to query the database.
https://docs.djangoproject.com/en/4.2/topics/db/models/#model-attributes

Maybe the documentation could be improved to remove Django-specific syntax.

**Comment by dimitri-b** [comment]
In the example code, the factory classes inherit from the plain Factory class, not ORM-enabled classes, which leads to confusion: not clear how it would work, given that nothing is returned from the RelatedFactory constructor, and no expected side effects are documented. At least with ORM-enabled parent classes, it would be easy to guess what will happen.

**Comment by francoisfreitag** [comment]
The `RelatedFactory` is not tied to a specific ORM. It just calls another factory **after** the base factory is created.
To clarify that behavior, the database foreign key comes to my mind first, in a 1-N relationship (say Author - Book, assuming a book is always written by a single author):

- the `SubFactory` allows to create an Author from the `BookFactory`. The Author must exist **before** a Book is created, so the `SubFactory` will create the Book **before** the Author.
- the `RelatedFactory` works somewhat in reverse. An AuthorFactory can use `RelatedFactory` to create a Book **after** an Author is created. An author does not need to have a Book, but it may be helpful to e.g. have more representative data.

**Comment by dimitri-b** [comment]
> The `RelatedFactory` is not tied to a specific ORM. It just calls another factory **after** the base factory is created. 

That much I understand, but if I don't tie it to ORM by inheriting from the right class, how can I access the objects generated by the `RelatedFactory`?
At least with the ORM link a table will be created in the specified database, but without such link - where is the generated data?

**Comment by francoisfreitag** [comment]
The link will depend on your project. https://factoryboy.readthedocs.io/en/stable/reference.html#factory.RelatedFactory.factory_related_name is passed as kwargs to the related factory. In the example, it is used to set `capital_of` on the related object, creating the link. That’s because Django will use values passed as kwargs for the model `__init__` for the model fields.
You can emulate this behavior by reading the kwarg during your related class `__init__` and saving it on the related object to keep the link.

**Comment by dimitri-b** [comment]
Now it all makes sense, thank you.
I guess, in my case it is possible to just override `__init__` and get it to populate some global collection.
In the end, I just used the SQLAlchemy option to generate DuckDB tables, it worked as expected without any hacking. :)
