### ISSUE TITLE
State of development

### ISSUE THREAD

**Issue by tildebox** [FactoryBoy/factory_boy#1027]
I work with Django and am looking for a package with which I can fill the database with example texts.

That's when I became aware of this package.

But am I right that this package is no longer being developed?

Can you recommend me another package?

**Comment by rbarrois** [comment]
Hi,

The project is still alive, and quite mature — hence the lowered activity on Github.
I know we haven't been able to get new releases out for some time, but most of the related issues have been fixed; a new one should be around within a week or two.

Did you get any unexpected issues trying to work with factory_boy? Please let us know if there are any bugs we're not (yet) aware of!

**Comment by rbarrois** [comment]
Release 3.3.0 is now out ;)
