### ISSUE TITLE
problem with properties that starts with underscore

### ISSUE THREAD

**Issue by rodrigobraga** [FactoryBoy/factory_boy#104]
_sorry my english_

I need use Factory Boy to create a object with one property that starts with underscore, but the object created does not have the value specified on the factory.

_factory_

```
class MyClassFactory(factory.django.DjangoModelFactory):
    FACTORY_FOR = app.MyClass
    _my_property = "foo bar"
```

_test_

```
foo = MyClassFactory()

# the code below print ''
print foo._my_property
```

What I do wrong?

**Comment by Pithikos** [comment]
This is great. But is there a way to configure factory_boy to **not ignore** the underscored fields? Namely, this becomes cumbersome if I have 20 metadata fields that start with underscore. And the factories start becoming unreadable.

**Comment by rbarrois** [comment]
@Pithikos the supported method would be to use [`class Meta:  rename`](https://factoryboy.readthedocs.io/en/latest/reference.html#factory.FactoryOptions.rename):
```python
class Meta:
    rename = {field: '_' + field for field in METADATA_FIELDS}
```

Or you could hook into private APIs (at your own risks) and write your own `Factory` subclass using a dedicated `FactoryOptions` subclass with an overloaded [`_is_declaration`](https://github.com/FactoryBoy/factory_boy/blob/master/factory/base.py#L328-L341) method.

You might see an example of defining a custom `Factory` / `FactoryOptions` class in the [`factory.django.DjangoModelFactory`](https://github.com/FactoryBoy/factory_boy/blob/master/factory/django.py#L90-L102) source.
