### ISSUE TITLE
make factory_boy documentation work with devdocs

### ISSUE THREAD

**Issue by matlads** [FactoryBoy/factory_boy#1042]
#### The problem
DevDocs combines multiple API documentations in a fast, organized, and searchable interface. The problem is that factory_boy documentation is not one of those supported at this time. Since one of devdocs best selling point is the offline

#### Proposed solution
My proposed solution is to use the [devdocs.io](devdocs.io) `thor docs:generate` script to target factory_boys documentation, and thus, potentially,  generate the index, manifest and offline data that devdocs needs to work.

#### Extra notes
I am not an expert on any of the above, but since I use [devdocs.io](devdocs.io) and `factory_boy` I would like to see a link between the two.

**Comment by rbarrois** [comment]
I have no issue with any third party including our documentation in their project :)

However, a quick glance at devdocs.io shows that they manage their list of included docs on their side; you'll have to open an issue there for them to include our docs.

Feel free to reopen this issue if an action is required on our end!
