### ISSUE TITLE
Unusable password generator for Django

### ISSUE THREAD

**Issue by jaap3** [FactoryBoy/factory_boy#1044]
#### The problem

The recently added `Password` generator for Django is helpful, but it's not clear how to use it to create an unusable password (similar to calling `set_unusable_password` on the generated user).

#### Proposed solution

Django's `set_unusable_password` is a call to `make_password` with `None` as the password argument:

https://github.com/django/django/blob/0b506bfe1ab9f1c38e439c77b3c3f81c8ac663ea/django/contrib/auth/base_user.py#L118-L120

Using `password = factory.django.Password(None)` will actually work (and will allow factory users to override the password if desired). However, currently the password argument to this factory is documented as a string and this option is not mentioned.

#### Extra notes

The default value of the `password` argument to `factory.django.Password` could also be set to `None`. This would make that factory generate unusable passwords by default, which may or may not be desired.

**Comment by francoisfreitag** [comment]
Thanks for reporting the issue!
Feel free to open a pull request to document the use of `None`.

As for the default, I believe we’re better off with the developer specifying their own value instead of providing a default out of the box. As you noted, it may or may not be desired. :+1:
