### ISSUE TITLE
Release new version ?

### ISSUE THREAD

**Issue by RemiDesgrange** [FactoryBoy/factory_boy#1082]
#### The problem

According to pypi, it seems that no release has been made for almost a year. I was looking at the code an noted that my local copy in my venv, fetched via `pip` did not contain the same code as on GitHub. Maybe time for 3.3.1 release ?

#### Proposed solution
 Release :-)

**Comment by johncarter-phntm** [comment]
Yes please! Would be great to get #1067 live , to fix "Maybe" (#965)

**Comment by bpneumann** [comment]
Seconded,  #1062 is also fixed in main but missing from 3.3.0.

**Comment by metaljoe** [comment]
Another vote for a release from me.
