### ISSUE TITLE
Setting id manually

### ISSUE THREAD

**Issue by andresespinosapc** [FactoryBoy/factory_boy#1107]
#### Description
If I set the id of a model manually, then the id of an instance created by a factory can collide.

#### To Reproduce
- Create an instance of a model setting `id=2`
- Create an instance of the same model without setting the `id`
- Try to create another instance of the same model without setting the `id`. You'll get an error, because the id "2" is already used.

##### Model / Factory code
```python
from django.db import models

class User(models.Model):
  pass

class UserFactory(factory.django.DjangoModelFactory):
  class Meta:
    model = User
```

##### The issue
It's self-explanatory with the description section.

```python
user1 = UserFactory(id=2)
user2 = UserFactory()
user3 = UserFactory()
```

**Comment by rbarrois** [comment]
Indeed, when you force the id your database does not increment its autoincrement sequence.

The available options are:
- Don't rely on explicit pks in your test setup (not always doable)
- Use some other code to alter the database's auto-sequence based on entries you've created.

For instance, you could use some code similar to that one (tuned for Postgres):

```python
def restart_pk_sequence(Model):
    max_pk = Model.objects.aggregate(Max("pk"))["pk__max")
    sequence_name = f"{Model._meta.db_table}_id_seq"
    with connection.cursor() as cursor:
        cursor.execute(f"ALTER SEQUENCE {sequence_name} RESTART WITH {max_pk + 1}")
```
And call that code after you've created your pk-restricted instances.

Note that factory_boy does not interact with the database's primary key management; this issue would happen in the exact same manner if you were calling `User.objects.create(...)` manually.
