### ISSUE TITLE
Enabling Pyscopg's connection pools causes integrity errors and unique violations

### ISSUE THREAD

**Issue by dhruvkb** [FactoryBoy/factory_boy#1109]
#### Description

Switching to Pyscopg's connection pools breaks fixtures in Django and raises integrity errors and unique violations.

#### To Reproduce

1. Consider https://github.com/WordPress/openverse.
2. Note that the CI + CD workflow is passing on `main`.
3. See PR WordPress/openverse#5210 that enables [connection pools](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-pools).
4. See that the [CI + CD workflow is failing](https://github.com/WordPress/openverse/actions/runs/12402429798/job/34624045702?pr=5210) on that PR.

The logs from that workflow run indicate

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint
```

and

```
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint
```

#### More info

More info such as the complete stack trace, and list of errors, is present in the workflow run logs.

**Comment by rbarrois** [comment]
I do not see any relation between your issue and our project.

The psycopg connection pooling feature should be managed within the Django settings of the parent using factory_boy; factory_boy does not configure or interact explicitly with any such settings.

I'm going to close this issue, as it lacks any actionable details on our end — I'm afraid I do not have enough free time to acquaint myself with third party CI/CD setups and code, unless I know what to look for in relation with this project.

However, please feel free to reopen it if you see some details on your end suggesting that the issue would actually stem from our code — ideally with a stack trace or some other code example.
