### ISSUE TITLE
TypeError: ModelBase object got multiple values for keyword argument 'date_joined'

### ISSUE THREAD

**Issue by EdwardIII** [FactoryBoy/factory_boy#132]
I can't seem to create a new user and pass in date_joined with an object based on `factory.django.DjangoModelFactory`, I see the error message `TypeError: ModelBase object got multiple values for keyword argument 'date_joined'`

```
from datetime import timedelta
from django.test import TestCase
from django.utils import timezone
import factory

class UserFactory(factory.django.DjangoModelFactory):
    FACTORY_FOR = User
    FACTORY_DJANGO_GET_OR_CREATE = ('email',)

    first_name = 'Terry'
    last_name = 'Wogan'
    username = factory.Sequence(lambda n: "twogan%d" % n)
    email = factory.Sequence(lambda n: "twogan%d@totp.com" % n)

    @classmethod
    def _create(cls, target_class, *args, **kwargs):
        """Override the default ``_create`` with our custom call."""
        manager = cls._get_manager(target_class)
        # The default would use ``manager.create(*args, **kwargs)``
        print kwargs
        return manager.create_user(*args, **kwargs)


class TestUserFactory(TestCase):
    def test_date_joined(self):
        date_for = timezone.now() - timedelta(days=15) 
        user = UserFactory(date_joined=date_for)
        self.assertEquals(date_for, user.date_joined)
```

**Comment by erkin7333** [comment]
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from full_settings.validators import PhoneValidator
from django.core.exceptions import ValidationError


class UserManager(BaseUserManager):
    def __create_user(self, username, password, *args, **kwargs):
        # username = PhoneValidator.clean(username)
        # if not PhoneValidator.validate(username):
        #     raise ValidationError("Telefon raqami emas")

        user = User(username=username)
        user.set_password(password)
        user.save()
        # pass


    def create_user(self, *args, **kwargs):
        kwargs.setdefault('is_staff', False)
        kwargs.setdefault('is_superuser', False)

        if kwargs.get('is_staff') or kwargs.get('is_superuser'):
            raise ValidationError("Xato")

        return self.__create_user(self, *args, **kwargs)


    def create_superuser(self, *args, **kwargs):
        kwargs.setdefault('is_staff', True)
        kwargs.setdefault('is_superuser', True)

        if not kwargs.get('is_staff') or not kwargs.get('is_superuser'):
            raise ValidationError("Xato")
        return self.__create_user(self, *args, **kwargs)


class User(AbstractUser):
    objects = UserManager()
    phone = models.CharField(max_length=14, default=None, blank=True, null=True,
                             unique=True, validators=[PhoneValidator()])
