### ISSUE TITLE
Support for SQLAlchemy Core ( without ORM )?

### ISSUE THREAD

**Issue by faliev** [FactoryBoy/factory_boy#133]
Is it possible to implement? If so, would you please tell me where to start?

**Comment by m-aciek** [comment]
@faliev Just for the record, did you suceed?

**Comment by pablobcb** [comment]
it would be great an example on how using it with table definitions instead of classes

**Comment by havok2063** [comment]
@faliev Did you end up implementing this?  If so, could you provide some examples?

**Comment by rbarrois** [comment]
@havok2063 I'll try to provide an example!

Assuming your table is defined like this:
```python
users = Table('users', metadata,
   Column('id', Integer, Sequence('user_id_seq'), primary_key=True),
   Column('name', String(50)),
   Column('fullname', String(50)),
   Column('nickname', String(50))
)
```

Then your factory could look like this:
```python
from myapp import get_connection  # To get your "engine.connection" class

class SQLAlchemyCoreFactory(factory.Factory):
    class Meta:
        abstract = True

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        connection = get_connection()
        result = connection.execute(model_class.insert().values(**kwargs))
        return result.inserted_primary_key

class UserFactory(SQLAlchemyCoreFactory):
    class Meta:
        model = users

    name = factory.Faker("name")
    fullname = factory.Faker("name")
    nickname = factory.Faker("first_name")

>>> UserFactory()
42
```

**Comment by havok2063** [comment]
Thanks @rbarrois this is helpful indeed.  It's a good starting point.  I was hoping for something that also enabled use of `build` and `create` but that might be too tied with the ORM version.  It's probably adaptable though with some work.  Now I just need to figure out to mock my functions and object methods that use sqla core to use an engine that can rollback inserts, and combine it with this.  It seems that factory boy only handles the creation and insertion of objects.

**Comment by rbarrois** [comment]
@havok2063 for a build vs. create you could simply have the `_build()` return the dict of values ;)

**Comment by havok2063** [comment]
@rbarrois Yeah good point. :)
