### ISSUE TITLE
Exception: AttributeError: 'module' object has no attribute 'fuzzy'

### ISSUE THREAD

**Issue by syabro** [FactoryBoy/factory_boy#138]
Got this strange exception with this code

``` python
import datetime
import factory
from client.factories import ClientFactory


class ProgramFactory(factory.django.DjangoModelFactory):
    FACTORY_FOR = 'program.Program'
    client = factory.SubFactory(ClientFactory)


class ProgramOutletFactory(factory.django.DjangoModelFactory):
    FACTORY_FOR = 'program.ProgramOutlet'
    program = factory.SubFactory(ProgramFactory)
    start_date = factory.fuzzy.FuzzyDate(datetime.date(2014, 1, 1), datetime.date(2014, 6, 1))
    end_date = factory.fuzzy.FuzzyDate(datetime.date(2014, 7, 1), datetime.date(2014, 12, 1))
```

If I include `import fuzzy` in factory/**init**.py it works.

**Comment by skolsuper** [comment]
I would say this is surprising behaviour, it certainly tripped me up.  I think that now  the factory.faker module is imported in factory.__init__.py (I gather it wasn't at the time of this ticket), it would be more consistent to do this with fuzzy too.  Either that or add the import statement to the first example in the docs.

**Comment by kylefox** [comment]
This tripped me up as well, thanks for posting this.

(Would be great to have that `import factory.fuzzy` mentioned in the docs)

**Comment by rbarrois** [comment]
@kylefox Good point, I've updated the docs accordingly.
