### ISSUE TITLE
delete old instance before creating new

### ISSUE THREAD

**Issue by guettli** [FactoryBoy/factory_boy#151]
To speed up unittesting, we don't delete the whole database before running each test.

This way a test needs to clean up old data before running.

Does factory boy support deleting before creating?

I could not find anything in the docs about deleting objects.

Do you have a hint how to implement a "delete before create" helper method?

Background: we use django, but don't use the "delete whole DB before each test" pattern.

**Comment by mobile-safari** [comment]
https://pythondev.space/questions/issue-with-django-test-when-using-factory-boy i see the way now
