### ISSUE TITLE
How to handle 'self' Foreign key relation in factory boy

### ISSUE THREAD

**Issue by muzaffaryousaf** [FactoryBoy/factory_boy#173]
Hello,

I've a django model where i'm using Foreign key with itself. Can you please guide me how i can replicate self relation in factory boy class.
e.g.

``` python
class A(models.Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', blank=True, null=True)
```

Please guide how i can create a factory for such type of relations.

Thanks.

**Comment by lcodyc4321** [comment]
Mr Barrois, why doesn't f = FakeModel.build(parent__parent=None) work, but  f = FakeModel(parent__parent=None) does work?

**Comment by rbarrois** [comment]
@lcodyc4321 That's the weird; could you open a new issue with the error message and the factory definition?

**Comment by mayela** [comment]
Hi everyone!
I have the same problem that @muzaffaryousaf, here my code
`class CitiesCountryFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = cities_models.Country
        django_get_or_create = ()
        
    code = 'mx'
    code3 = 'mex'
    population = random.randint(100, 20000)
    area = random.randint(200, 100000)
    currency = 'mxn'
    currency_name = 'Moneda nacional'
    currency_symbol = '$'
    language_codes = 'es'
    phone = '+52'
    continent = factory.SubFactory(CitiesContinentFactory)
    tld = 'TLD'
    postal_code_format = '06870'
    postal_code_regex = '06780'
    capital = 'Mexico City'
    neighbours = factory.SubFactory('apps.locations.factories.CitiesCountryFactory')`

Thanks in advance

**Comment by Maxcutex** [comment]
Having the same issue and the above doesnt solve it for me ... anyone has any update?

**Comment by elebow** [comment]
The above suggestion was no longer working for me, so I accomplished a self-referential factory with a `LazyAttribute` that is a recursive function:

https://gist.github.com/elebow/d3158afd7c5674e4ff95b89271b7ae7d

**Comment by Kub-AT** [comment]
```
class AFactory(factory.Factory):
    class Meta:
        model = models.A
    name =  factory.Sequence(lambda n: "a%d" % n)
    parent = factory.LazyAttribute(lambda x: AFactory(parent=None))
```

**Comment by hammerheadlemon** [comment]
Not having any luck with this - would have thought there would have been a nice solution by now!

**Comment by rsmithlal** [comment]
I've used FactoryBoy traits to allow for an optional self-referential foreign key and prevent the recursion issue.

```python
class CategoryFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Category

    name = factory.Sequence(lambda n: "category-%s" % n)
    parent_category = None

    class Params:
        subcategory = factory.Trait(
            parent_category = factory.SubFactory('posts.tests.factories.CategoryFactory')
        )

CategoryFactory.create_batch(5, subcategory=True)
```

**Comment by laalamrajesh** [comment]
@muzaffaryousaf 
if you just want to create one parent then you could do like below
`class AFactory(factory.Factory):
    class Meta:
        model = models.A
    name =  factory.Sequence(lambda n: "a%d" % n)
    parent = factory.SubFactory('myproj.myapp.factories.AFactory', **parent=None**)
`

**Comment by laalamrajesh** [comment]
> Well, the simplest way would be to define a self-referential factory:
> 
> ```python
> # myproj/myapp/factories.py
> class AFactory(factory.Factory):
>     class Meta:
>         model = models.A
>     name =  factory.Sequence(lambda n: "a%d" % n)
>     parent = factory.SubFactory('myproj.myapp.factories.AFactory')
> ```
> 
> Then, you'll just have to define the target depth when calling:
> 
> ```python
> a = AFactory(parent__parent__parent__parent=None)
> ```
> 
> I've added a test on that topic, too.

I am thinking that we need to inherit ```python factory.django.DjangoModelFactory``` instead ```python factory.Factory```

**Comment by davidroeca** [comment]
In my case, I wanted None to be the default for a parent, but still had some trouble getting it to work. Lazy attributes helped here, for anyone else who's still looking for an alternative:

```python
class ChildFactory(factory.alchemy.SQLAlchemyModelFactory):
    """Factory for ``app.models.Child`` model"""

    class Meta:
        model = app.models.Node
        sqlalchemy_session = db.session

    class Params:
        parent = None

    id = factory.LazyFunction(uuid.uuid4)
    value = factory.Faker("domain_word")

    parent = factory.LazyAttribute(lambda obj: obj.parent)
    parent_id = factory.LazyAttribute(
        lambda obj: None if obj.parent is None else obj.parent.id
    )
```

**Comment by caprioara** [comment]
```python
# django_media_player/src/api/tests/factories.py
class ZoneFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Zone

    name = factory.LazyAttribute(lambda x: faker.name())
    assigned_static_zone_id = factory.SubFactory('django_media_player.src.api.tests.factories.ZoneFactory')
```

```python
# django_media_player/src/api/tests/test_api_zone.py

class TestZone(APITestCase):
    def setUp(self):
        self.test_zone = ZoneFactory(parent__parent__parent__parent__parent__parent=None)
```

Can somebody help me? It doesn't work

**Comment by Shodiev-Shokhrukh** [comment]
> > Well, the simplest way would be to define a self-referential factory:
> > ```python
> > # myproj/myapp/factories.py
> > class AFactory(factory.Factory):
> >     class Meta:
> >         model = models.A
> >     name =  factory.Sequence(lambda n: "a%d" % n)
> >     parent = factory.SubFactory('myproj.myapp.factories.AFactory')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, you'll just have to define the target depth when calling:
> > ```python
> > a = AFactory(parent__parent__parent__parent=None)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've added a test on that topic, too.
> 
> I am thinking that we need to inherit ` factory.django.DjangoModelFactory` instead ` factory.Factory`

Above solution does not work for me even inheriting from factory.django.DjangoModelFactory
