### ISSUE TITLE
adding fake models from yaml

### ISSUE THREAD

**Issue by cchildersmedi** [FactoryBoy/factory_boy#223]
I have a model that I cannot create (the model does not allow saving, it is loaded from yaml) but other models depend on it. Since build() is not accepting parent__parent=None, I am getting recursion limit when trying to use build(). I cannot use create(), because of the save() being overridden to not allow new saves. There is no documentation available to load yaml to a specific, individual model, which I need to instantiate the required model

**Comment by rbarrois** [comment]
Sorry for never being able to look into this :(

Feel free to reopen an issue with more details if you're still meeting those bugs ;)
