### ISSUE TITLE
Wire together `random` from FactoryBoy hooks to Faker's random seed

### ISSUE THREAD

**Issue by jeffwidman** [FactoryBoy/factory_boy#275]
Per https://github.com/rbarrois/factory_boy/pull/247#issuecomment-189897331

**Comment by punchagan** [comment]
Initializing FactoryBoy with a random seed (using `reseed_random`, for instance) should also set the seed for Faker.  I currently work around this, by setting the seed for Faker myself.

**Comment by rbarrois** [comment]
Yes, that's the goal here.

Last time I checked, the hooks in Faker didn't allow to handle the random seed finely enough.

The API in ``factory_boy`` allow to:
* Display the used "random state" after the test run
* Reuse a previous seed afterwards

If the APIs in faker have improved, it would be easy to adjust the hooks in ``factory.fuzzy`` accordingly.
