### ISSUE TITLE
Need a recipe for circular dependencies

### ISSUE THREAD

**Issue by nferrari** [FactoryBoy/factory_boy#28]
As discussed today on IRC, we need a simple way to manage circular dependencies:

A.b --> B
B.a --> A

Thanks!

**Comment by davidmarquis** [comment]
For the benefit of others (and my future self) who could come here: 

`CircularSubFactory` has been deprecated in 2.0.0.

Using a [`RelatedFactory`](https://factoryboy.readthedocs.io/en/stable/reference.html#factory.RelatedFactory) with the `factory_related_name` is the better option.
