### ISSUE TITLE
KeyError when value not provided for field listed in django_get_or_create

### ISSUE THREAD

**Issue by rrauenza** [FactoryBoy/factory_boy#287]
I have something like:

```
class Album:
    ...

class Track:
    album = ForeignKey(Album)
    ....

```

When I make the factories, I have:

```
class AlbumFactory:
    ...

class TrackFactory:
    class Meta:
        model = Track
        django_get_or_create = ('album', 'name')
    # I don't specify Album here -- I want to force users to pass an album to factory
    name = ... # track name
```

I seem to get a KeyError in TrackFactory because the key 'album' doesn't exist.  But it _is_ a valid field.

Here's the actual stack trace.  The actual field is 'dashboard':

```
  File "/opt/perfdash/factory_boy.git/factory/base.py", line 519, in _generate
    obj = cls._prepare(create, **attrs)
  File "/opt/perfdash/factory_boy.git/factory/base.py", line 494, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/opt/perfdash/factory_boy.git/factory/django.py", line 172, in _create
    return cls._get_or_create(model_class, *args, **kwargs)
  File "/opt/perfdash/factory_boy.git/factory/django.py", line 160, in _get_or_create
    key_fields[field] = kwargs.pop(field)
KeyError: 'dashboard'
```

Is it not valid to intentionally leave out some fields in the factory to force specifying them upon creation?

**Comment by rbarrois** [comment]
It should work here.

I see a ``dashboard`` in your error message, which does not appear in your example.

Could you pass a full factory + stack trace?

**Comment by rrauenza** [comment]
The example is a simplified/renamed version of my code.

Ah, wait -- I've misidentified which of my unit tests was triggering this.  Now I understand why it happens -- it's when I create the equivalent of a Track through the TrackFactory but didn't pass the required Album to the TrackFactory().  So instead of getting an error about not having an (eventually) required field (since it is defined as not null), I get a premature KeyError because you can't setup key_fields for get_or_create because the field isn't in kwargs.

The pull request I submitted a little while ago may make this situation confusing because the error message is not accurate now that I understand this better.

(See _get_or_create() and _create() in factory/django.py)

**Comment by rrauenza** [comment]
So... my error message in my pull request should not be:

"Unable to find field named '%s' in model %s"

But rather...

"Unable to find initialization value for '%s' in factory %s" % (field, cls.__name__)

**Comment by federicobond** [comment]
I believe this is now fixed. Feel free to reopen if that's not the case.

**Comment by danmash** [comment]
@federicobond I have similar issues when I try to use 
`django_get_or_create = ('id',)`

```
class UserProfileFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = UserProfile
        django_get_or_create = ("id",)
        
    user = factory.SubFactory(UserFactory)
```
I get `errors.FactoryError: django_get_or_create - Unable to find initialization value for 'id' in factory UserProfileFactory`

if I omit `django_get_or_create = ("id",)`
then I get `django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_pkey"`

**Comment by danwald** [comment]
@danmash I was seeing the same issue:
The work around was me using another field that was explicitly defined in the factory or adding `id factory.Faker('random_int')` to your factory.
HTH
