### ISSUE TITLE
Meta: move to a github organization?

### ISSUE THREAD

**Issue by rbarrois** [FactoryBoy/factory_boy#314]
As the project is growing and welcoming new contributors, I think it would make sense to move it to its own organization.

Pros:
* As a community project, it's more welcoming when not "under a user's account"
* The organisation could welcome related projects, e.g https://github.com/rbarrois/django-factory_boy / https://github.com/cam-stitt/factory_boy-peewee / https://github.com/anentropic/factoryboy-gaendb

Cons:
* Obsolete links
* We'd need to find a logo ;)

What do you think?

**Comment by rbarrois** [comment]
NB: I have reserved https://github.com/FactoryBoy, should we decide to go this way and under that name.

**Comment by jeffwidman** [comment]
I have no issues with it. We aren't at a stage that we require it, but it would be simpler to pull things together under one umbrella (for those owners who are interested in moving their third-party extensions, obviously not all will want that.)

Most common reason I hear for project owners keeping projects under their own handle as a resume of sorts. 

Conversely though, when I'm evaluating a library, if it has it's own org, it's a signal that the owner is more open to external suggestions and letting the project grow "beyond" just the owner. So I'm more inclined to use those projects.

It's your call.

**Comment by ekohl** [comment]
> Cons:
> 
>     Obsolete links

When you move a project in Github, it will build redirects so while they should be changed, it shouldn't break things.

**Comment by rbarrois** [comment]
Thanks for the input :) I'm going to launch this as soon as I kind find some time :)

**Comment by jeffwidman** [comment]
This has been done now. :-)
