### ISSUE TITLE
Problem with multiprocessing module

### ISSUE THREAD

**Issue by ultimatecoder** [FactoryBoy/factory_boy#317]
I created child class of [DjangoModelFactory](http://factoryboy.readthedocs.io/en/latest/orms.html#the-djangomodelfactory-subclass). Calling create_batch() method using 4 worker process of the same model class. It works but the data is duplicate.

For example,
I am calling 4 worker process with argument of create_batch(3) then as a result it create 3 similar records for all 12 records. 1,2,3 are same in data. 4,5,6 are same in data. 7,8,9 are same in data, 10,11,12 are same in data.

**Comment by rbarrois** [comment]
Answered on the factoryboy@groups.google.com mailing list: https://groups.google.com/forum/#!topic/factoryboy/plZd3B7LBHY
