### ISSUE TITLE
A simple MyFactory.create() actually not saving in DB?

### ISSUE THREAD

**Issue by ppython** [FactoryBoy/factory_boy#329]
Hello,

I just gave a try to factory_boy, and it fails to actually save my model in DB.

Here's my model:
```
# myapp.models.py
from custom_user.models import AbstractEmailUser


class User(AbstractEmailUser):
    class Meta:
        verbose_name = _(u'Utilisateur')
```

Here's my factory:
```
# myapp.factories.py
import factory

from myapp.models import User


class UserFactory(factory.Factory):
    class Meta:
        model = User

    email = factory.Sequence(
        lambda n: 'user_%d@mail.com' % n)
```

What I'm reading from the docs:
```
# Returns a saved User instance
user = UserFactory.create()
```

And here's how I'm trying to use the whole thing:

- Vanilla style, everything works just fine:
```
In : User.objects.all().count()
Out: 15
In : User.objects.create(email="test@mail.com")
In : User.objects.all().count()
Out: 16
```

- With factory_boy:
```
In : User.objects.all().count()
Out: 16
In : user_created_with_factory = UserFactory()
In : User.objects.all().count()
Out: 16
In : user_created_with_factory.id
In : user_created_with_factory.email
Out: 'user_24@mail.com'
```
That's where it should return `17` for `user_created_with_factory.id`
I also tried with `UserFactory.create()` instead of `UserFactory()`, same result.
Of course, if I try `user_created_with_factory.save()`, I'll have my instance in DB and have an ID...

My env:
python: 2.7.6
Django: 1.10
Pip: pip 1.5.4
Virtualenv: 1.11.4
factory-boy: 2.7.0

Any ideas of what could be wrong with my procedure !?
Thanks

**Comment by rbarrois** [comment]
Hi!

If you work with Django models, you need to use ``factory.django.DjangoModelFactory`` — otherwise, factory_boy uses the "simple Python object" approach.

Note that factory_boy also supports other ORMs (SQLAlchemy, ...).

Hope this helps!

**Comment by ppython** [comment]
YES,
Thanks @rbarrois , it was that simple and straightforward, in plain sight :

> ORM Support
> factory_boy has specific support for a few ORMs, through specific factory.Factory subclasses:
> Django, with factory.django.DjangoModelFactory

Next time I'll RTFM in it's entirety.
Thank you and factory_boy team.

**Comment by mecampbellsoup** [comment]
Hey guys - I'm having the opposite issue: when invoking `UserFactory.build()` I'm finding that it always persists the record:

```python
In [8]: user = UserFactory.build()
/Users/mattysoup/Sites/Code/tradeblock/platform/.venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField User.date_joined received a naive datetime (2018-07-16 17:02:15.435178) while time zone support is active.
  RuntimeWarning)
/Users/mattysoup/Sites/Code/tradeblock/platform/.venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField User.password_reset_expires received a naive datetime (2018-07-17 17:02:15.435502) while time zone support is active.
  RuntimeWarning)

In [9]: user.pk
Out[9]: 14
```

Any ideas? Thanks! :)

**Comment by jyr** [comment]
Hi, 

I have the same problem and I'm using factory.django.DjangoModelFactory on 2 models, the first is works but the second no.

```
import factory

from .models import Location, Station


class LocationFactory(factory.django.DjangoModelFactory):

    class Meta:
        model = Location

    name = factory.Faker('slug')
    latitude = factory.Faker('latitude')
    longitude = factory.Faker('longitude')


class StationFactory(factory.django.DjangoModelFactory):

    class Meta:
        model = Station

    location = LocationFactory()
    order = factory.Faker('random_number')
    is_active = factory.Faker('boolean')
```

Thanks.

**Comment by rbarrois** [comment]
@jyr since this issue has already been closed, it would be easier for us to track it if you open a separate issue.

Also, your use of ``location = LocationFactory()`` won't work the way you expect it to; you should be using ``location = factory.SubFactory(LocationFactory)``.
