### ISSUE TITLE
FuzzyDate does not return same date when seed is set

### ISSUE THREAD

**Issue by punchagan** [FactoryBoy/factory_boy#331]
`FuzzyDate` takes a `start_date` and an `end_date` argument -- the `end_date` being optional.  When no `end_date` is provided, `datetime.date.today()` is used as the default value. 

When using `factory_boy` with a specific seed, one would expect anything that uses `FuzzyDate` to return the same date, each time.  But, when the code is run on two different days, the `end_date` is different because of the default value being different.  This causes the randomly generated dates to be off. 

Here is a [simplified version](https://gist.github.com/punchagan/6d2b1535726f0d917a387dd7e88d2047) of `FuzzyDate`'s code to explain the bug.

**Comment by jeffwidman** [comment]
This makes sense, and I agree it's a bug. I'm not sure the best way to solve it though, as `datetime.date.today()` seems like a sensible default. 

Adding a note to the docs makes the most sense, and possibly adding a warning to the code that fires if you declare a seed without also declaring an `end_date`.

**Comment by rbarrois** [comment]
Another option would be to force ``end_date`` to be similar to ``start_date + datetime.timedelta(days=10)``, which would be more stable.

I'd rather avoid linking the default end date to the random seed, however.

Finally, if you want reproducible tests, it might be interesting to freeze time as well (e.g with https://pypi.python.org/pypi/freezegun).

**Comment by punchagan** [comment]
> Adding a note to the docs makes the most sense, and possibly adding a warning to the code that fires if you declare a seed without also declaring an end_date.

Adding a note in the docs doesn't sound like enough, to me.  Adding a warning is definitely an option. 

> Another option would be to force end_date to be similar to start_date + datetime.timedelta(days=10), which would be more stable.

Yes, I was initially thinking of something like this with `days=365`. 

> Finally, if you want reproducible tests, it might be interesting to freeze time as well (e.g with https://pypi.python.org/pypi/freezegun).

I am aware of `freezegun`, and thanks for the note.

**Comment by punchagan** [comment]
I've something that raises a warning [here](https://github.com/punchagan/factory_boy/commit/229ce1951f31dbe8be700f949d8de4d81fc7979c).  Let me know what you think.

**Comment by jeffwidman** [comment]
Can you submit that as a Pull Request against this project?

I'm generally in favor of it, although the warning message itself shouldn't say "you must do this" but rather something along the lines of "Setting a specific random seed for FuzzyDate can still have varying results unless you also set a specific end date. For details see [link to this issue]"

**Comment by punchagan** [comment]
@jeffwidman Sorry for the delay in responding to this, but I've finally opened a PR for this: #346
