### ISSUE TITLE
factory.iterator lazy?

### ISSUE THREAD

**Issue by andreav** [FactoryBoy/factory_boy#332]
Hi,
I have some code like this:

```
class TopicPrivateTripFactory(TopicPrivateFactory):
    topic = factory.SubFactory(TopicTripFactory, category=factory.Iterator(STCategory.objects.filter(slug="private")))
```

I'm not creating TopicPrivateTripFactory inside my tests, however 
I see factory.Iterator issues a query anyway, before test starts.
It seems like this is done during factories module import.
Is it possible to make it lazy (so no query is issued at all)?

Thank you!

**Comment by rbarrois** [comment]
That's weird, we have explicit tests to guard against this behaviour:
https://github.com/FactoryBoy/factory_boy/blob/master/tests/test_using.py#L1652

Would you have a stack trace leading to the DB call?

**Comment by andreav** [comment]
Thank you for your reply.
I just upgraded from 2.4.1 to 2.7 and the problem disappeared.

Thank you again for this great module!
