### ISSUE TITLE
DESCRIPTION.rst and METADATA still refer to fake-factory

### ISSUE THREAD

**Issue by jisantuc** [FactoryBoy/factory_boy#340]
`factory_boy` no longer relies on `fake-factory`, but in `METADATA` and `DESCRIPTION.rst` there's still:

> For this, factory_boy relies on the excellent `fake-factory <https://pypi.python.org/pypi/fake-factory>`

Super minor and I'm happy to PR it, I just haven't set up dev for `factory_boy` before

**Comment by jeffwidman** [comment]
PR welcome. You actually don't need to setup dev as it's just a docs change... don't even need to clone the repo locally, just modify directly using the Github web interface and it will fork, make the modification, and prompt you to submit a PR.

**Comment by jisantuc** [comment]
Fixed in #341
