### ISSUE TITLE
Using mute_signals for test classes in django tests

### ISSUE THREAD

**Issue by abdulhaq-e** [FactoryBoy/factory_boy#348]
Currently decorating a test class with `mute_signals` has no effect. It only works if the class is based on `Factory`. Sometimes, one wants to decorate the test class rather than the factories themselves.

```python
@factory.django.mute_signals(signals.pre_save)
class TestViews:
    
   def test_1():
       pass

   def test_2():
       pass
```

Is there a way to do it. If not I can give it a go and submit a PR that attempts this change.

**Comment by rbarrois** [comment]
That's an interesting suggestion!

However, I'd argue that this isn't part of factory_boy's scope: disabling signals during tests bears little relation to creating fixtures in the database; I only added the ``mute_signals`` helper to save users the need to override each factory's ``_create`` hook.

I think you should bring this suggestion to the Django issue tracker or mailing list, or maybe write a dedicated module ;)
