### ISSUE TITLE
factory.Trait() cannot get a factory.RelatedFactory override

### ISSUE THREAD

**Issue by jrobichaud** [FactoryBoy/factory_boy#351]
Traits does not seem to allow a related factory override.

Ex:
```python
class MyModelFactory(factory.django.DjangoModelFactory):
    class Meta:
          model = models.MyModel
    class Params:
        with_my_other_model = factory.Trait(
             my_other_model=factory.RelatedFactory(MyOtherModelFactory, 'my_model')
        )
```

It will complain `my_other_model` is not a valid field.

That would be awesome.

**Comment by rbarrois** [comment]
That's indeed a bug.

It should be fixed through a partial core refactor which I have started recently :)

**Comment by jrobichaud** [comment]
Thank you very much!

**Comment by rbarrois** [comment]
@jrobichaud This should be fixed on master; could you try it on your repository?

If you have the time to contribute a test example (somewhere around https://github.com/FactoryBoy/factory_boy/blob/master/tests/test_using.py#L1102), that would be awesome!

Thanks :)

**Comment by jrobichaud** [comment]
I will take a look at this, thanks!

**Comment by jrobichaud** [comment]
I found a regression using nested traits with same name:

```
class SomeModelFactory(factory.django.DjangoModelFactory):
    class Meta:
          model = models.SomeModel
    with_awesome_values = factory.Trait(
          some_awesome_value="4321"
    )
class MyModelFactory(factory.django.DjangoModelFactory):
    class Meta:
          model = models.MyModel
    some_model = factory.SubFactory(SomeModelFactory)
    class Params:
        with_awesome_values = factory.Trait(
             awesome_value="1234"
             some_model__with_awesome_values=True
        )
```

`factory.errors.CyclicDefinitionError: Cyclic lazy attribute definition...`

`with_awesome_values` would be defined in both but are not cyclic at all.

**Comment by jrobichaud** [comment]
Another regression:

This Trait blows up everything even without using `super_user=True`.
It has something to do that if the value does not exist in the factory it not use the model's default value anymore and try to set `None`.

```
class UserFactory(factory.DjangoModelFactory):
    class Meta:
        model = models.User

    username = factory.Sequence(lambda n: "user_%d" % n)
    first_name = factory.Faker('first_name')
    last_name = factory.Faker('last_name')
    email = factory.LazyAttribute(lambda a: '{}@example.com'.format(fake.pystr()).lower())

    class Params:
        super_user = factory.Trait(
            is_superuser=True,
            is_staff=True,
            is_active=True,
        )
```

`sqlite3.IntegrityError: NOT NULL constraint failed: auth_user.is_superuser`

**Comment by jrobichaud** [comment]
It seems as well that LazyAttribute is now only evaluation once. By example the same value which blows up of validation on unique fields.
If you use the factory:
```
class UserFactory(factory.DjangoModelFactory):
    class Meta:
        model = models.User

    username = factory.Sequence(lambda n: "user_%d" % n)
    first_name = factory.Faker('first_name')
    last_name = factory.Faker('last_name')
    email = factory.LazyAttribute(lambda a: '{}@example.com'.format(fake.pystr()).lower())
```

With this test:
```
class TestUser(TestCase):
    def test_email_not_equal(self):
        a = factories.UserFactory()
        b = factories.UserFactory()
        self.assertNotEqual(a.email, b.email)
```

`AssertionError: 'fzjebrwcesfkmbiwdbfn@example.com' == 'fzjebrwcesfkmbiwdbfn@example.com'`

**Comment by rbarrois** [comment]
Thanks for the input! I'll look into it soon.

I think I know why you're having an issue with the ``super_user`` trait; I'll have to add some kind of sentinel ``NotProvided`` value if the trait is not overriding anything.

The ``LazyAttribute`` one looks surprising though.

**Comment by jrobichaud** [comment]
I created a pull request exposing the three issues: https://github.com/FactoryBoy/factory_boy/pull/373

Finally the third issue had nothing to do with LazyAttribute but with Faker/fake. It appears that now the random seed is reinitialized all the time.

**Comment by jrobichaud** [comment]
You can see the failures on Travis:
https://travis-ci.org/FactoryBoy/factory_boy/jobs/220400469

```

======================================================================
FAIL: test_random (tests.test_django.DjangoFakerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/FactoryBoy/factory_boy/tests/test_django.py", line 579, in test_random
    self.assertNotEqual(o1.foo, o2.foo)
AssertionError: 'GXsaMKlLEUxriPwYMkAE' == 'GXsaMKlLEUxriPwYMkAE'
----------------------------------------------------------------------
```

**Comment by kamotos** [comment]
@jrobichaud Good catch ! I think this [commit](https://github.com/FactoryBoy/factory_boy/commit/e426ab973b3dbcc5302a32b457519ee13574dcf4#diff-1bb0938cc13c98b73fc81b284aa9933eR80) introduced the regression in the third test you wrote, I will see if there is a way to get around it.

**Comment by jrobichaud** [comment]
@kamotos / @rbarrois will you considerer merging my Pull Request? I think these extra tests could be useful to avoid potential future regressions.

**Comment by rbarrois** [comment]
@jrobichaud Definitely! Any test that can detect regressions or check that advanced usecases work properly is welcomed :)

**Comment by jrobichaud** [comment]
@rbarrois I did not answer to your request to create tests/examples for the `Traits` and `RelatedFactory` since regressions were more important. I will do it.

**Comment by rbarrois** [comment]
@jrobichaud your tests are enough to expose the issue in Traits :-)

The second issue (with the cycle error) exposed a complex bug in the proposed API for ``factory.Maybe``, I think I should have fixed ready soonish ;)

**Comment by rbarrois** [comment]
@jrobichaud I've just sent a few changes to your branch at https://github.com/jrobichaud/factory_boy/pull/1; these should fix your two examples.

I'll let @kamotos look at the third issue — he's the one who spent the most time in that section of the code.

Can you check whether the updated version would fix your issue?

**Comment by jrobichaud** [comment]
@rbarrois see my comment : https://github.com/jrobichaud/factory_boy/pull/1#issuecomment-293394644

**Comment by jrobichaud** [comment]
I believe you could just merge the PR as-is and fix the code on master. These tests do not cause regressions, they bug are on master and real.

**Comment by jrobichaud** [comment]
I think found why the PR did not work! My IntelliJ Idea setup is awkward and it was using a Egg I build instead of the factory folder in the project.

**Comment by jrobichaud** [comment]
@rbarrois  I merged your PR, now you can merge mine.

**Comment by jrobichaud** [comment]
I confirm it is the line pointed out by @kamotos.
```
        cls._FAKER_REGISTRY[locale].random.setstate(get_random_state())
```
This code should be called only once (for all locales) when the reseed function is called.

**Comment by kamotos** [comment]
I think #376 should solve the problem. Let me know what you think.

**Comment by rbarrois** [comment]
@jrobichaud All new tests have been fixed, and merged to master.

I'm closing this — all should be fine now!

Thanks again for your help :)

**Comment by jrobichaud** [comment]
I was trying to document the Traits and RelatedField and I realized it does not work.

See this PR for a test: https://github.com/FactoryBoy/factory_boy/pull/378

**Comment by HeyHugo** [comment]
So overriding RelatedFields inside Traits does not work? I think I've encountered this, although I'm using sqlalchemy classes.
```
AttributeError: 'RelatedFactory' object has no attribute '_sa_instance_state'
```

**Comment by maximderbin** [comment]
Have the same issue as @HeyHugo
