### ISSUE TITLE
Check support for Python 3.6

### ISSUE THREAD

**Issue by rbarrois** [FactoryBoy/factory_boy#358]
With Python 3.6 out, we should make sure that it is properly supported by factory_boy.

This should work out of the box; but some steps are required to check it:
1. Add Python 3.6 to https://github.com/FactoryBoy/factory_boy/blob/master/tox.ini
2. Add that build in https://github.com/FactoryBoy/factory_boy/blob/master/.travis.yml
3. Make a pull request, wait for the travis build, and check that it's still working.
4. Update ``README.rst`` and classifiers at https://github.com/FactoryBoy/factory_boy/blob/master/setup.py#L57 to state that Python 3.6 is supported.

**Comment by mbaechtold** [comment]
May I suggest to split the "bonus idea" into separate issues?

**Comment by rbarrois** [comment]
@mbaechtold good point; done.

**Comment by jeffwidman** [comment]
@mbaechtold do you mind also adding the python 3.6 to the shields.io badge? (just modify the readme) 

Thanks!

**Comment by mbaechtold** [comment]
Sure, I'll do that tomorrow.

**Comment by rbarrois** [comment]
@jeffwidman I'm wondering if the shields.io wouldn't be based on the PyPI metadata; in which case they would update automatically once we release a version, but not before :confused:

**Comment by jeffwidman** [comment]
@rbarrois is totally right; I just forgot.
