### ISSUE TITLE
Remove stated support for Django<1.8

### ISSUE THREAD

**Issue by rbarrois** [FactoryBoy/factory_boy#363]
We don't have a clear support policy, but the Django team no longer supports Django<1.8; let's remove it as well.

This means:
- Removing it from the tox.ini matrix
- Removing it from the README.rst and other docs, if needed
- Finding any code that looks for ``django.version`` and remove code paths used for Django<1.8

**Comment by mbaechtold** [comment]
According to https://www.djangoproject.com/download/, Django 1.8 will at least be supported until at least April 2018. Will you really already remove support of Django 1.8?

**Comment by rbarrois** [comment]
@mbaechtold No, I just intend to remove support for versions older than 1.8, i.e 1.7 and before.

**Comment by mbaechtold** [comment]
Of course. It's right there, in the title of this issue: Django<1.8

**Comment by rbarrois** [comment]
Closed by @kamotos through #370 !

**Comment by kamotos** [comment]
@rbarrois #371 solves the last bullet point I think.
