### ISSUE TITLE
Add support for pypy3

### ISSUE THREAD

**Issue by rbarrois** [FactoryBoy/factory_boy#364]
The PyPy team has added support for Python 3 (see https://morepypy.blogspot.it/2017/03/pypy27-and-pypy35-v57-two-in-one-release.html).

We should add this to our test matrix:
- In the tox.ini file
- In the travis.yml test setup
- In the setup.py "classifiers / implementation" section
- In the README.rst

Implementation should be:
1. Add those changes
2. Make a pull-request
3. Check that all goes fine
4. Add yourself to the CREDITS file if this is your first contribution
5. Enjoy!

**Comment by sideris** [comment]
Hi. Would we need to update the tox `envlist` as well? I don't see pypy27 there.

**Comment by YPCrumble** [comment]
Just leaving a note for future visitors - this has been closed by https://github.com/FactoryBoy/factory_boy/commit/e55493d7aa7aebead8fd5f689503477cb0c00e0e

**Comment by rbarrois** [comment]
@YPCrumble thanks for the notification, I had forgotten to close the issue :/
