### ISSUE TITLE
Chaining decorators : post_generation and lazy_attribute

### ISSUE THREAD

**Issue by kaizenseed** [FactoryBoy/factory_boy#383]
So my use case is this

```python
class TransactionFactory(factory.DjangoModelFactory):
    """
        Factory used to instantiate class Transaction
        """

    class Meta:
        model = Transaction

    created_by = factory.SubFactory(PersonFactory)
    amount = factory.Faker('money')
    category = None

    # see http://factoryboy.readthedocs.io/en/latest/recipes.html#simple-many-to-many-relationship
    @factory.post_generation
    def tags(self, create, extracted, **kwargs):
        if not create:
            # Simple build, do nothing.
            return

        if extracted:
            # A list of tags were passed in, use them
            for tag in extracted:
                self.tags.add(tag)
```

Here the Transaction model has category as a FK and tags as M2M field. The constraint is that transaction MUST have at least one of tag or category set. Also each tag is mapped to a list of allowed categories the transaction can take.

In the normal course (ie if tags was not M2M) i'd use lazyAttribute on category, check what all tags are there n pick one of the allowed value. But since tags are generated post_generation.. what do i do?

I was thinking of chaining post_generation and lazy_attribute decorators like

```
@factory.lazy_attribute
@factory.post_generation
def category(self, create, extracted, **kwargs):
    # do something here
```

But i'm not sure if these 2 decorators are intended to ever be chained... Could someone explain what the begaviour would be in such a case. Also if this is not a good approach, what should I use?

Thanks

**Comment by rbarrois** [comment]
Hi!

``@factory.post_generation`` is executed *after* you object has been saved to the database.
In its code, ``self`` is the generated object, not a factory instance (there is a bit of black magic behind the scenes).

So you should be able to perform any operations you might want on that object, e.g:

```python
@factory.post_generation
def category(self, create, extracted, **kwargs):
    self.category = random.choice([tag.category for tag in self.tags.all()])
```

Does that help?

**Comment by francoisfreitag** [comment]
Assuming it did help, we can close the 6 years old issue.
