### ISSUE TITLE
Create a pydict Faker with value_types ...

### ISSUE THREAD

**Issue by mhubig** [FactoryBoy/factory_boy#387]
I'm trying to create a `pydict` faker with only string values to populate a JSONField. So fare I've tried the following methods without look: 

    extra = factory.Faker('pydict', nb_elements=10, value_types=['str'])
    -> TypeError: pydict() got an unexpected keyword argument 'value_types'

    extra = factory.Faker('pydict', nb_elements=10, ['str'])
    -> SyntaxError: positional argument follows keyword argument

    factory.Faker('pydict', nb_elements=10, 'str')
    -> SyntaxError: positional argument follows keyword argument

    extra = factory.Faker('pydict', 10, True, 'str')
    -> TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given

How can I specify the `*value_types` part of the pydict faker?

**Comment by mhubig** [comment]
I found a way ... but not a very nice one:

```
def fake_dict():
    from faker import Faker
    fake = Faker()
    return fake.pydict(10, True, 'str')

class TemplateWidgetFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.TemplateWidget

    extra = factory.LazyFunction(fake_dict)
```

**Comment by jsonbateman** [comment]
I just ran into this today and it seems to me that factoryboy's `Faker.__init__.py` does not have a way to support any providers that would use `*varargs` even if they were properly written. I might be misinterpreting, but it seems factoryboy only ever looks at the `**kwargs`.
