### ISSUE TITLE
Managing randomness with faker is impossible

### ISSUE THREAD

**Issue by scheparev-moberries** [FactoryBoy/factory_boy#389]
In the case when the fields are specified over faker providers, it's impossible to manage randomness because order of evaluation is not fixed (iterating a dict internally?).
Example:
Seed the random before of instantiation of 
```
class CompanyFactory(factory.DjangoModelFactory):
    class Meta:
        model = Company

    name = faker.company
    status = 'APR'
```
with 

```
import factory
faker = factory.faker.Faker._get_faker(locale='de_DE')
faker.random.seed(0)
```
returns the same result. But adding any other fuzzy field, for instance:
```
faker.phone_number
```
makes both fields to be filled in an unpredictable way. Maybe because the fields are evaluated in the dict iteration.
It would be nice to have a work around at least.

**Comment by rbarrois** [comment]
Hi,

Maybe this is simply due to the shortened example you've pasted, but I think that we should do:

```python
class CompanyFactory(factory.django.DjangoModelFactory):
    name = factory.Faker('company')
```

Here, ``factory.Faker`` will handle the connection with ``faker``; the code you're using would use the same name for every company.

**Comment by scheparev-moberries** [comment]
It was working sporadically without using a lazy attirubute, so the actual is
```
name = factory.LazyFunction(faker.company)
```
I'll check your notation

**Comment by scheparev-moberries** [comment]
Still got random results with 
```
class CompanyFactory(factory.DjangoModelFactory):
    class Meta:
        model = Company

    name = factory.Faker('company', locale='de')
    phone = factory.Faker('phone_number')
```

**Comment by scheparev-moberries** [comment]
UPD: it only happens in my unit tests, when I try to instantiate the factory from the django console with seeding in one statement, the result persists. I got totally no idea what is happening in between, because in both cases I instantiate the factory *right after* the seeding.

**Comment by rbarrois** [comment]
Thanks!

So this is indeed a bug; which version do you use?

**Comment by scheparev-moberries** [comment]
`factory_boy==2.8.1`

**Comment by rbarrois** [comment]
I've just released version 2.9.0, can you check whether the bug is still there?

There have been many fixes to the faker-related code, and improvements to the core of factory_boy in that release.

Thanks!

**Comment by scheparev-moberries** [comment]
Unfortunately the problem persists with the version 2.9.0

**Comment by rbarrois** [comment]
Have you tried with version 2.9.2?

Can you paste a stripped-down unit test where you have the issue?

**Comment by scheparev-moberries** [comment]
Model:
```
class Company(models.Model):
    name = models.CharField(blank=False, max_length=255)
    phone = models.CharField(default='', blank=True, max_length=40)
    about = models.TextField(default='', blank=True)
    street = models.CharField(default='', blank=True, max_length=255)
    postcode = models.CharField(default='', blank=True, max_length=14)
    website = models.URLField(default='', blank=True, max_length=255)

    created_at = CreationDateTimeField()

```

Factory and test:
```
import factory

faker = factory.faker.Faker._get_faker(locale='de_DE')


class TestFactory(factory.DjangoModelFactory):
    class Meta:
        model = Company

    name = factory.LazyFunction(faker.company)
    phone = factory.LazyFunction(faker.phone_number)
    about = factory.LazyFunction(faker_en.bs)
    street = factory.LazyFunction(faker.street_name)
    postcode = factory.LazyFunction(faker_en.zipcode)
    website = factory.LazyFunction(faker.url)
    created_at = factory.LazyFunction(faker.date_time_this_year)


class TestRandomCrash(TestCase):
    def test_random(self):
        faker = factory.faker.Faker._get_faker(locale='de_DE')
        faker.random.seed(0)
        print(TestFactory().name)

```


I've updated to 2.9.2, the behavior persists. Run the test multiple times, company names remains random

**Comment by rbarrois** [comment]
As stated above, this is not the supported way of interacting with faker from factory_boy.

Please try again with:

```python
class TestFactory(factory.DjangoModelFactory):
    class Meta:
        model = Company

    name = factory.Faker('company')
    phone = factory.Faker('phone_number')
    about = factory.Faker('bs')
    street = factory.Faker('street_name')
    postcode = factory.Faker('zipcode')
    website = factory.Faker('url')
    created_at = factory.Faker('date_time_this_year')
```

**Comment by scheparev-moberries** [comment]
Tried it, still the same

**Comment by joecridge** [comment]
Seeing this also in 2.9.2: any factory using factory.Faker() for more than one attribute is non-deterministic when called in a test, but works fine in the Django shell.

**Comment by joecridge** [comment]
I’ve followed the issue back to `utils.sort_ordered_objects`:

```python
def sort_ordered_objects(items, getter=lambda x: x):
    return sorted(items, key=lambda x: getattr(getter(x), OrderedBase.CREATION_COUNTER_FIELD, -1))
```

What happens here is that all the factory.Faker() attributes have the same creation counter, and so `sorted` just iterates over `items` dictionary to sort amongst them, resulting in unpredictable ‘sorted’ output.

@rbarrois I’m not sure what the fault is here: does `sort_ordered_objects` assume that the creation counters are unique (in which case the counter code is at fault), or is `sort_ordered_objects` supposed to handle repeated counter values deterministically (in which case it’s implementation needs to sort the corresponding keys alphabetically)?

**Comment by chongkim** [comment]
I just cloned factory_boy and ran the test using `make test` (or `python -m unittest tests`.  It came back with

```Ran 377 tests in 0.770s

OK (skipped=1)```.  But when I ran `python -m unittest tests.test_using`, it came back with ```======================================================================
FAIL: test_same_seed_is_used_between_fuzzy_and_faker_generators (tests.test_using.RepeatableRandomSeedFakerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chongkim/github/factory_boy/tests/test_using.py", line 2334, in test_same_seed_is_used_between_fuzzy_and_faker_generators
    self.assertEqual(students_1[0].two, students_2[0].two)
AssertionError: 'William Brown' != 'Mark Peterson'
- William Brown
+ Mark Peterson


----------------------------------------------------------------------
Ran 138 tests in 0.127s

FAILED (failures=1, skipped=1)```

**Comment by chongkim** [comment]
I've fixed the problem in https://github.com/FactoryBoy/factory_boy/pull/438

**Comment by chongkim** [comment]
I've made a PR.  I noticed that some PR are years old.  What do I need to do to get this into master?  I'd hate to have it sit around for some step I neglected to do.

**Comment by rbarrois** [comment]
Thanks for the analysis, and for @chongkim analysis.

Actually, the issue was not in the use of sorted declarations, but in the improper configuration of faker's random generator :)

**Comment by stefanjcollier** [comment]
Great work guys!
