### ISSUE TITLE
How to debug factories problems

### ISSUE THREAD

**Issue by apelliciari** [FactoryBoy/factory_boy#39]
Hi,

i'm trying to use factory boy with some nested factories but i get a PRIMARY KEY error (.. must be unique).

these are my factories

``` python
class CategoryParentFactory(factory.Factory):
    FACTORY_FOR = Category
    parent = None
    name = "foo"

class CategoryFactory(factory.Factory):
    FACTORY_FOR = Category
    parent = factory.SubFactory(CategoryParentFactory)
    name = "bar"

class ProductFactory(factory.Factory):
    FACTORY_FOR = Product
    category = factory.SubFactory(CategoryFactory)
    name = "fuz"
```

if i try something like 

``` python
cp = CategoryParentFactory.create()
c = CategoryFactory.create()
```

it works, but

``` python
p = ProductFactory.create()
```

gives me "IntegrityError: PRIMARY KEY must be unique"

How can i debug/understand what happens?

Thanks,

ps: i'm trying to get many products with a single category, so this

``` python
p1 = ProductFactory.create(category=c)
p1 = ProductFactory.create(category=c)
```

gives me the same error

Alessandro

**Comment by oesah** [comment]
I had the same issue, unfortunately the traceback gave zero information. But reading this thread, I also found that something in my pre_save receivers in Django caused this error. Thanks for the hint!
