### ISSUE TITLE
Factory Boy returning different type_id for Generic Foreign Key

### ISSUE THREAD

**Issue by kousiknath33** [FactoryBoy/factory_boy#390]
I have a model like the following:
```python
class MyModel(TimeStampedModel):
    entity_type = models.ForeignKey(ContentType)
    entity_id = models.PositiveIntegerField(db_index=True)
    entity = GenericForeignKey('entity_type', 'entity_id')
    other_field = .....
```

Now I create entry in the table like following:
```python
my_object = SomeModel.objects.create()
MyModel.objects.create(entity=my_object)
```

And I query MyModel like:
```python
MyModel.objects.filter(entity_id=my_object.id,
    entity_type_id=ContentType.objects.get_for_model(SomeModel).id)
```

The select query does not return anything.
By logging I found out that while running tests in factory boy, the entity_type_id that gets created while inserting the object is different than what is returned by ContentType.objects.get_for_model(SomeModel).id

Please suggest what I can do to get the test done.

**Comment by jeffwidman** [comment]
Is this Django's ORM? I don't recognize the model names...

**Comment by kousiknath33** [comment]
yes it's django ORM.

**Comment by rbarrois** [comment]
@kousiknath33 Could you show your factories for ``SomeModel`` and ``MyModel``?

Right now, there is no factory_boy-related code in your example ;)

**Comment by philgyford** [comment]
I'm having what I think is the same problem, using [django-contrib-comments](https://github.com/django/django-contrib-comments), which attaches comments to other models using a GenericForeignKey.

From my `project/weblogs/models.py`:

    from django.db import models

    class Post(models.Model):
        title = models.CharField(blank=False, max_length=255)
        # etc.
From my `project/custom_comments/models.py`:

    from django_comments.models import Comment

    class CustomComment(Comment):
        # Some custom methods.



My `project/custom_comments/test_models.py`:

**Comment by jeffwidman** [comment]
Closing due to lack of information, if you add more info we can re-open and re-examine.
