### ISSUE TITLE
Release a Version

### ISSUE THREAD

**Issue by safwanrahman** [FactoryBoy/factory_boy#392]
Its while ``factory-boy`` has not release any version to pypi. A lot of improvements are made in the meantime and we can not get it untill a release has been made.

Is it possible to make a new version release soon?

**Comment by rbarrois** [comment]
Sorry for the long delay :/

I've just pushed the release, and improved the tooling to allow for easier (and, hopefully, more frequent) releases.

Thanks for pinging us on that topic ;)
