### ISSUE TITLE
Release factory_boy

### ISSUE THREAD

**Issue by brmzkw** [FactoryBoy/factory_boy#395]
Hi,

The last release is broken, which has been fixed by 86b0781411bf2730b6ee03877b6eed686ff1ae82
Do you intend to make a patch release soon?

**Comment by rbarrois** [comment]
How is it broken? I see no issue on my side:

```
% python -V
Python 2.7.12

% pip install factory_boy
Collecting factory-boy
  Downloading factory_boy-2.9.0-py2.py3-none-any.whl
Collecting Faker>=0.7.0 (from factory-boy)
  Downloading Faker-0.7.18-py2.py3-none-any.whl (620kB)
    100% |████████████████████████████████| 622kB 790kB/s 
Collecting python-dateutil>=2.4 (from Faker>=0.7.0->factory-boy)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 196kB 2.2MB/s 
Collecting six (from Faker>=0.7.0->factory-boy)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting ipaddress (from Faker>=0.7.0->factory-boy)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Installing collected packages: six, python-dateutil, ipaddress, Faker, factory-boy
Successfully installed Faker-0.7.18 factory-boy-2.9.0 ipaddress-1.0.18 python-dateutil-2.6.1 six-1.10.0
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by brmzkw** [comment]
Running `easy_install factory-boy` is broken without the fix. Even if easy_install is broken in so many ways we should never call it and use pip instead, it is how nosetests installs test dependencies.

To reproduce, create a setup.py such as:

```python
from setuptools import find_packages, setup

setup(
    name='xxx',
    version='0.0.1',
    packages=find_packages(),
    install_requires=[],
    tests_require=['factory-boy'],
)
```

and run `python setup.py nosetests`. Since nose install the dependencies in `tests_require` with easy_install, the following error message is raised:

```
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
	section: [zest.releaser]
	option : tag-format
	key    : version
	rawval : v%%(version)s
```

**Comment by brmzkw** [comment]
To be more clear:

You pushed to package in [pypi.python.org](https://pypi.python.org/pypi/factory_boy/2.9.0): a .whl and a .tar.gz. The wheel is completely fine, the source is not. Running `pip install --no-binary ':all:' factory-boy` which installs from the source release and not from the whl also breaks.

**Comment by rbarrois** [comment]
OK, I see what you mean.

To sum it up: installing from source (e.g with easy_setup or nosetests) under Python 2 is broken with the current release.

I'll make a new release in the next days; however, I'd suggest to move away from eazy_install (deprecated) or nose ([unmaintained](http://nose.readthedocs.io/en/latest/#note-to-users); use nose2 instead?).

**Comment by brmzkw** [comment]
I didn't even know about the existence of nose2. But anyway the problem still persists with it, since nose2 also uses distutils to install requirements specified in `tests_requires`.

**Comment by rbarrois** [comment]
@brmzkw I've made that new release, can you confirm that this is fixed for you?

**Comment by brmzkw** [comment]
yep that's ok! Our unittests are back to green thanks to you :)

Thanks a lot
