### ISSUE TITLE
factory.Maybe doesn't work with factory.RelatedFactory

### ISSUE THREAD

**Issue by tonial** [FactoryBoy/factory_boy#397]
I'm trying to set a RelatedFactoy combine with Maybe, so that it's only created if a condition is fulfiled .

```
class PaymentModeFactory(factory.DjangoModelFactory):
    class Meta:
        model = models.PaymentMode

    kind = enums.MANUAL
    authorization = factory.Maybe(
        factory.LazyAttribute(lambda o: o.kind = enums.WITH_AUTH),
        factory.RelatedFactory(PaymentModeAuthorizationFactory, 'payment_mode'),
    )
```

Whenever the Maybe condition is True (and only if True) the _create() method is given a authorization key in it's kwargs. The value is the RelatedFactory we defined.

**Comment by twheys** [comment]
By "does't work well" you mean it doesn't work at all :( 

From reading the source, it seems that there are 'pre' and 'post' build steps. `RelatedFactory` and PostGeneration are both 'post' steps and everything else is a 'pre' step. By wrapping `RelatedFactory` in a maybe, it gets included as a 'pre' step, which is incorrect.

**Comment by tonial** [comment]
Yes, indeed, it was a understatement. I've just changed the issue title to make it clearer.

**Comment by twheys** [comment]
I ran into this myself when using RelatedFactory in traits. I suppose it also wouldn't work with any other type of post declaration. 

I am new to factory_boy but I will try my hand at it.
