### ISSUE TITLE
'PostGenerationContext' object has no attribute 'items'

### ISSUE THREAD

**Issue by Fingel** [FactoryBoy/factory_boy#400]
In https://github.com/FactoryBoy/factory_boy/commit/8dadbe20e845ae7e311edf2cefc4ce9e24c25370
PostGenerationContext was changed to a NamedTuple. This causes a crash in utils.log_pprint:110

AttributeError: 'PostGenerationContext' object has no attribute 'items'

PR with a quick fix here: https://github.com/FactoryBoy/factory_boy/pull/399

**Comment by rbarrois** [comment]
Thanks!

I've merged your fix, it's good for that kind of debug statements :)
