### ISSUE TITLE
How to use RelatedFactory for a model without related_name?

### ISSUE THREAD

**Issue by pavan-blackbuck** [FactoryBoy/factory_boy#403]
```
class User(Model):
  name = CharField(max_length=100)

class Order(Model):
  user = ForeignKey(User)
```
I access the list of orders for a user using as `user.order_set.all()` which is working for me. Ref: https://stackoverflow.com/a/42080970/1080135

But when I try to use the RelatedFactory as follows, I get an error saying that User does not have the attribute "order_set"
```
class UserFactory(DjangoModelFactory):
  class Meta:
    model = User
  order_set = RelatedFactory(Order, 'user')
```

**Comment by rbarrois** [comment]
Hi,

Looking at your code, you should be calling ``RelatedFactory(OrderFactory, 'user')``.
A call to ``UserFactory()`` would then do something similar to: ``user = User.objects.create(...); OrderFactory(user=user)``.

Can you check your ``RelatedFactory`` definition?

**Comment by pavan-blackbuck** [comment]
My mistake. It seems to be working now.
