### ISSUE TITLE
Mention more `fuzzy.random` changes in changelog

### ISSUE THREAD

**Issue by hannosch** [FactoryBoy/factory_boy#404]
I have a custom BaseFuzzyAttribute and so far used:
```
factory.fuzzy.random.randint(100000, 999999)
```
to generate a base value and than do some other things with it.

The docs at https://factoryboy.readthedocs.io/en/latest/fuzzy.html#managing-randomness say I should use ``factory.fuzzy._random`` now, but this doesn't exist.

Instead I now need to use:
```
factory.random.randgen.randint(100000, 999999)
```

Would be nice if this change was called out more explicitly in the changelog and the docs would be fixed.

**Comment by jeffwidman** [comment]
Agreed. We just haven't had time to make progress on https://github.com/FactoryBoy/factory_boy/issues/271
