### ISSUE TITLE
No module named 'faker.config'

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [FactoryBoy/factory_boy#406]
Hello dear friends,

I use Python 3.6 with Anaconda distribution.

I have just installed factory_boy with pip `pip install factory_boy==2.9.2`.

In the dependencies I have the following:
- factory_boy==2.9.2
- Faker==0.7.18

And when I want to load the library I got the following message:

```python
>>> import factory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\GITPRO~1\FEEDCR~1.IO\venv\lib\site-packages\factory\__init__.py", line 26, in <module>
    from .faker import Faker
  File "C:\GITPRO~1\FEEDCR~1.IO\venv\lib\site-packages\factory\faker.py", line 23, in <module>
    import faker.config
ModuleNotFoundError: No module named 'faker.config'
```

Which is for me quite ... disturbing ... I have tried other versions, but never seemed to make it work ...

Thanks a lot for your help.

Jonathan

**Comment by rbarrois** [comment]
This looks like a bug.

Can you show us the output of ``pip freeze`` related to ``Faker`` and ``factory_boy``?

According to the ``Faker`` repository, ``faker.config`` exists since version 0.5.2: https://github.com/joke2k/faker/commit/ae6fc126aa94de9b8c2a41d9602cfb29b930b135

Can you try to run, in a shell:
```python
>>> import faker
>>> import faker.config
>>> import factory.faker
```

Thanks!

**Comment by DEKHTIARJonathan** [comment]
Okay, I'm really sorry ...
I have reinstalled my python environment because this bug seemed absurd to me... 
I recreated my virtualenv and now everything works fine... Very sorry @rbarrois but thanks anyway.

I'm closing this

**Comment by glassresistor** [comment]
Saw error but I'm using virtualenv

```bash
ipython 
Python 3.6.2 (default, Aug  4 2017, 14:35:04) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import faker.config
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-e84b0e376978> in <module>()
----> 1 import faker.config

ModuleNotFoundError: No module named 'faker.config'

In [2]: import faker

In [3]: import factory.faker
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-4d55b47f7a51> in <module>()
----> 1 import factory.faker

/home/mikela/code/intake/intake-zappa/lib/python3.6/site-packages/factory/__init__.py in <module>()
     24 )
     25 
---> 26 from .faker import Faker
     27 
     28 from .declarations import (

/home/mikela/code/intake/intake-zappa/lib/python3.6/site-packages/factory/faker.py in <module>()
     21 
     22 import faker
---> 23 import faker.config
     24 
     25 from . import declarations

ModuleNotFoundError: No module named 'faker.config'

**Comment by glassresistor** [comment]
pip freeze
amqp==2.1.4
argcomplete==1.9.2
asn1crypto==0.22.0
autopep8==1.3.2
awscli==1.11.160
base58==0.2.4
beautifulsoup4==4.4.1
behave==1.2.5
behave-django==0.5.0
billiard==3.5.0.3
boto==2.48.0
boto3==1.4.7
botocore==1.7.18
celery==4.1.0
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
click==6.7
codeclimate-test-reporter==0.2.3
colorama==0.3.7
coverage==4.4.1
cryptography==2.0.3
decorator==4.1.2
defusedxml==0.5.0
dj-database-url==0.4.2
Django==1.10.7
django-allauth==0.32.0
django-appconf==1.0.2
django-compressor==2.1.1
django-debug-toolbar==1.4
-e git://github.com/rossettistone/django-easy-audit.git@bf6c070e134fd557ffad0779b4b856afb555cf71#egg=django_easy_audit
django-extensions==1.9.0
-e git://github.com/bee-keeper/django-invitations@173524d7c462fbd6193421f67009f3d394c1a232#egg=django_invitations
django-jinja==2.3.1
django-storages==1.6.5
django-taggit==0.22.1
django-url-robots==2.0
djangorestframework==3.6.4
docutils==0.14
durationpy==0.5
factory-boy==2.9.2
Faker==0.7.18
future==0.16.0
futures==3.1.1
gunicorn==19.7.1
hjson==3.0.0
idna==2.6
ipdb==0.10.3
ipython==5.4.1
ipython-genutils==0.2.0
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
kombu==4.1.0
lambda-packages==0.16.1
MarkupSafe==1.0
mixpanel==4.3.2
newrelic==2.70.0.51
oauthlib==2.0.2
olefile==0.44
parse==1.8.2
parse-type==0.3.4
pep8==1.7.0
pexpect==4.2.1
phonenumbers==8.8.0
pickleshare==0.7.4
Pillow==4.2.1
placebo==0.8.1
prompt-toolkit==1.0.15
psycopg2==2.7.3.1
ptyprocess==0.5.2
pyasn1==0.3.6
pycodestyle==2.3.1
pycparser==2.18
Pygments==2.2.0
PyJWT==1.5.2
pyOpenSSL==17.2.0
PySocks==1.6.7
python-dateutil==2.6.1
python-http-client==1.2.3
python-Levenshtein==0.12.0
python-slugify==1.2.4
python3-openid==3.1.0
pytz==2016.10
PyYAML==3.12
rcssmin==1.0.6
reportlab==3.4.0
requests==2.18.4
requests-oauthlib==0.8.0
rjsmin==1.0.12
rsa==3.4.2
s3transfer==0.1.10
sendgrid==2.2.1
sendgrid-django==2.0.0
simplegeneric==0.8.1
six==1.11.0
smtpapi==0.3.1
sqlparse==0.2.3
toml==0.9.3
tqdm==4.17.1
traitlets==4.3.2
troposphere==1.9.5
twilio==6.1.0
ua-parser==0.7.3
Unidecode==0.4.21
urllib3==1.22
user-agents==1.1.0
vine==1.1.4
wcwidth==0.1.7
Werkzeug==0.12
whitenoise==3.3.0
wsgi-request-logger==0.4.6
-e git+git@github.com:Miserlou/Zappa.git@c18e164255b80a1d25c55d6e5d94b6089dfd1933#egg=zappa

**Comment by adnanmuttaleb** [comment]
Same problem for me, it seems as bug. I have two env with same requirements, but one completely created from scratch and one update (from fake-factory to Faker), for the last one I have same error:
```
ModuleNotFoundError: No module named 'faker.config'
```

**Comment by adnanmuttaleb** [comment]
After checking, I think the problem might be the following:

```
lib/python3.9/site-packages/faker# pip show Faker
Name: Faker
Version: 10.0.0
Summary: Faker is a Python package that generates fake data for you.
Home-page: https://github.com/joke2k/faker
Author: joke2k
Author-email: joke2k@gmail.com
License: MIT License
Location: .../lib/python3.9/site-packages
Requires: text-unidecode, python-dateutil
Required-by: factory-boy
```

As you can see the version is `10.0.0`, but when showing the conent of *Faker* in *site-packages*:

```
lib/python3.9/site-packages/faker# ls
__pycache__  contrib  exceptions.py  providers  proxy.py  py.typed  typing.py  utils
```

This contradict with the actual contents of version `10.0.0`. Still, I do not know what actually caused the problem I think because I had *fake_factory* prior to *Faker*.

**Comment by rbarrois** [comment]
@adnanmuttaleb It's likely because you installed `faker` on top of `fake-factory`, yet both use the same module name.
`pip` hasn't removed `fake-factory` before installing `faker`, and now the folder holds files from both packages.

Just a quick note: `pip` is a package *installer*, not a package *manager*: it doesn't keep track of which packages you've explicitly asked for, and which where installed as dependencies for other packages, and can now be removed.

When in doubt, just recreate your virtualenv!

**Comment by sandeepbol** [comment]
> @adnanmuttaleb It's likely because you installed `faker` on top of `fake-factory`, yet both use the same module name. `pip` hasn't removed `fake-factory` before installing `faker`, and now the folder holds files from both packages.
> 
> Just a quick note: `pip` is a package _installer_, not a package _manager_: it doesn't keep track of which packages you've explicitly asked for, and which where installed as dependencies for other packages, and can now be removed.
> 
> When in doubt, just recreate your virtualenv!

Words of wisdom! Kudos! Did help me :)
