### ISSUE TITLE
Choices for CharField not selected properly

### ISSUE THREAD

**Issue by leblowl** [FactoryBoy/factory_boy#412]
Either I am using this wrong or there is a bug here. I can't find any help on this online. But I could be blind. It's not the first time I haven't noticed something in plain sight.

Here is the relevant part of my model:
```
class Event(django.db.models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_ERROR = 'error'

    STATUSES = (
        (STATUS_NEW, 'New'),
        (STATUS_IN_PROGRESS, 'In progress'),
        (STATUS_ERROR, 'Error')
    )
    status = models.CharField(max_length=16, choices=STATUSES, default=STATUS_NEW)
```

Relevant part of model factory:
```
class EventFactory(DjangoModelFactory):
    class Meta:
        model = Event

    status = 'new',
```

When I instantiate this factory, `status` gets set to `"('new',)"`. I expected it would be set to `'new'`.
`"('new',)"` isn't even a choice. Thanks for the very helpful library!

**Comment by rbarrois** [comment]
That's very weird; are you sure you don't have a trailing comma anywhere?

In python, ``x = 'foo',`` is the same as ``x = ('foo', )``...

How do you get this ``status == ('new',)`` part? Can you show the relevant section of the test where you instantiate the factory?

NB: In your snippet, ``class Event()`` doesn't inherit from Django's model; is that actually the case in your code?

**Comment by leblowl** [comment]
@rbarrois Thanks for the insight. It was a trailing comma. I wasn't aware that a trailing comma would do that. Good to know. The snippet obviously wasn't very accurate! I've updated it to reflect my issue better. Thanks for the help.
