### ISSUE TITLE
Create a List SubFactory

### ISSUE THREAD

**Issue by sohaibfarooqi** [FactoryBoy/factory_boy#415]
Hi,
I have following `mongoengine` model:

    Class A(Document):
          address = ListField(Address)

Where `Address` is an embedded document.
How can I make a factory of this model? Below is an example of what I want to achieve.

     Class AFactory(factory.Factory):
               class meta:
                        model = A
                address = factory.<List>SubFactory(Address)

Thanks

**Comment by rbarrois** [comment]
You can use [`factory.List`](http://factoryboy.readthedocs.io/en/latest/reference.html#factory.List):

```python
class AFactory(factory.Factory):
    class Meta:
        model = A

    address = factory.List([
        factory.SubFactory(AddressFactory),
        factory.SubFactory(AddressFactory),
    ])
```

If you need to alter the behaviour of one of the addresses, you could then do ``AFactory(address__1__planet="Pluto")``, for instance.

**Comment by g-kartik** [comment]
What if we want to alter a field of all subfactories in the list?
