### ISSUE TITLE
Django: Custom attributes for the Factory class

### ISSUE THREAD

**Issue by Antonboom** [FactoryBoy/factory_boy#420]
Hello! Thanks for the wonderful library!

I would like to do something like
```python
class UserFactory(factory.DjangoModelFactory):
    
    PASSWORD_LENGTH = 10
    password = factory.PostGenerationMethodCall(
                   'set_password', factory.Faker('password', length=PASSWORD_LENGTH))

    class Meta:
        model = User
```

But it raises _"factory/django.py, line 165, in __create TypeError: 'PASSWORD_LENGTH' is an invalid keyword argument for this function."_.

Is there a way to define attributes for a class that are **not related** to the model?
Can the library ignore fields starting with '_' or '__', for example?

Temporary solution
```python
class CustomAttrsMixin(factory.Factory):

    class Meta:
        abstract = True

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        for attr, attr_value in kwargs.copy().items():
            if attr.startswith('_'):
                del kwargs[attr]

        # noinspection PyProtectedMember
        return super()._create(model_class, *args, **kwargs)
```

In addition, you can use inheritance
```python
class UserWithAttrs(UserFactory):
    _password = '15$Gs42h#8'     # <- This will not cause an exception when UserWithAttrs()
```

**Comment by rbarrois** [comment]
It does ;)
Or you can add it to the [`exclude`](https://factoryboy.readthedocs.io/en/latest/reference.html#factory.FactoryOptions.exclude) option of `class Meta`.

**Comment by Antonboom** [comment]
Thanks! Excuse for troubling.
