### ISSUE TITLE
Mixing factory instances and native Django model instances breaks unittests

### ISSUE THREAD

**Issue by chrisspen** [FactoryBoy/factory_boy#422]
Maybe I'm missing something from the docs, but I've run into a huge roadblock with factory-boy.

I have a simple schema like:

    class Category(models.Model):

        name = models.CharField(max_length=100, unique=True)

    class Distributor(models.Model):

        name = models.CharField(max_length=100, unique=True)

        category = models.ForeignKey(Category)

    class Company(models.Model):

        name = models.CharField(max_length=100, unique=True)

        distributor = models.ForeignKey(Distributor)

The category instances are fixed, so I don't need factory-boy to auto-generate them. I load them in via a fixture at the start of my unittests. I also load some distributor instances in via a fixture, but I still need to randomly generate new ones.

The problem I've run into is that factories don't seem to play nicely with pre-existing instances loaded in via fixtures. For example, I first tried building my factories like:

    CAT_ID_TO_DATA = dict((r['pk'], r['fields']) for r in json.load(open('categories.json')))

    class CategoryFactory(factory.DjangoModelFactory):

        id = factory.fuzzy.FuzzyChoice(CAT_ID_TO_DATA.keys())
    
        name = factory.LazyAttributeSequence(lambda o, n: CAT_ID_TO_DATA[o.id])

        class Meta:
            model = Category

    class DistributorFactory(factory.DjangoModelFactory):

        name = factory.Faker('company')

        category = factory.SubFactory(CategoryFactory)

        class Meta:
            model = models.Distributor

    class CompanyFactory(factory.DjangoModelFactory):

        name = factory.Faker('company')

        distributor = factory.SubFactory(DistributorFactory)

        class Meta:
            model = models.Company

My unittest looks like:

    def test_create_company(self):

        company = CompanyFactory()
        company.save()
        print('company:', company.id)
        self.assertEqual(Company.objects.all().count(), 1)

This fails with with a unique ID constraint error, because the CategoryFactory does an insert instead of an update, which collides with the pre-loaded category records.

So I thought, this should be a simple fix. Just modify my Distributor.save to assign a default category and remove the CategoryFactory altogether, right? That left me with:

    class DistributorFactory(factory.DjangoModelFactory):

        name = factory.Faker('company')

        class Meta:
            model = models.Distributor

    class CompanyFactory(factory.DjangoModelFactory):

        name = factory.Faker('company')

        distributor = factory.SubFactory(DistributorFactory)

        class Meta:
            model = models.Company

Imagine my surprise when my unittest then output:

    company: 1
    Traceback (most recent call last):
        tests.py
               self.assertEqual(Company.objects.all().count(), 1)
    AssertionError: 0 != 1

So, now that I'm mixing factory-created instances with fixture-loaded instances, that's somehow caused the factory-created instances to exist outside of my unittest's transaction, rendering them unqueryable.

I tried re-writing my factory to do the category lookup inside `_prepare` like:

    class DistributorFactory(factory.DjangoModelFactory):

        name = factory.Faker('company')

        class Meta:
            model = models.Distributor

            @classmethod
            def _prepare(cls, create, **kwargs):
                kwargs['category'] = Category.objects.get(id=1)
                return super(DistributorFactory, cls)._prepare(create, **kwargs)

but that resulted in a similar error.

Is this a bug or am I doing something wrong? I'm using `Django==1.11` and `factory-boy==2.9.2`.

**Comment by chrisspen** [comment]
Digging into the code, I realized the problem is on my end. The issue was that I was using `_prepare()`, which was removed a few versions ago, and some custom logic I needed to have run was being skipped, causing the empty query. I've upgraded this and now it's fixed.

**Comment by jeffwidman** [comment]
Thanks for following up, much appreciated.
