### ISSUE TITLE
Add support of Mimesis's data providers

### ISSUE THREAD

**Issue by lk-geimfari** [FactoryBoy/factory_boy#423]
How about supporting Mimesis which has more data providers and has not any side dependencies.

I have created this issue in the repository of [Mimesis](https://github.com/lk-geimfari/mimesis/issues/244#issuecomment-335023201). And i want to understand where this feature must be implemented, in factory_boy or in Mimesis.

I think that both libraries will only benefit if you'll support Mimesis's data providers in factory_boy.

**Comment by stephenross** [comment]
You might want to look at putting this kind of request in to the Faker project instead of factory_boy as Faker is used to generate the randomized data.

**Comment by lk-geimfari** [comment]
This has been implemented in other project: [mimesis-factory](https://github.com/mimesis-lab/mimesis-factory).

**Comment by michael0liver** [comment]
This would be a great addition to `factory-boy`. mimesis is much faster than faker and provides many different data providers! I already use the project `mimesis_factory`. It would be nice if the `faker` integration was optional.
