### ISSUE TITLE
How to create Profile.username with faker?

### ISSUE THREAD

**Issue by legshort** [FactoryBoy/factory_boy#426]
I wanna create random value with `faker` [wrapper](http://factoryboy.readthedocs.io/en/latest/reference.html#faker), however, I can't get extract any value from it.

```python
# not working
username = factory.Faker('profile')['username']
```

Has anyone done this before?

**Comment by etiology** [comment]
Q1. What does a "username" look like to you?
  - do you want an email address?
    ```python 
          username = factory.Faker('email')
    ```
  - do you want a random string?
   ```python 
          username = factory.Faker('words', nb_words=2)
    ```

I don't recall 'profile' being in Faker's provider list but I can't verify that because I'm not in front of a computer that can run Python right now. 

Let me know if you have further issues and I can update this later.

**Comment by etiology** [comment]
Here is an updated example of what I think you want.  If you have specific implementation details about the model class or the ORM you're using then please post them.

```python
import factory

class Profile(object):
    def __init__(self, **kwargs):
        self.username = kwargs.get('username')
        self.first_name = kwargs.get('first_name')
        self.last_name = kwargs.get('last_name')

    def __repr__(self):
        return "Profile(username='{s.username}', first_name='{s.first_name}', last_name='{s.last_name}')".format(s=self)

class ProfileFactory(factory.Factory):
    class Meta:
        model = Profile
    username = factory.Faker('email')
    first_name = factory.Faker('first_name')
    last_name = factory.Faker('last_name')

```

Output: 
```python
print(ProfileFactory())
# Profile(username='mullinstabitha@logan.com', first_name='Christine', last_name='Fry')

print(ProfileFactory(first_name='foo', last_name='bar'))
# Profile(username='donnasilva@russo.net', first_name='foo', last_name='bar')

**Comment by jeffwidman** [comment]
Thanks @etiology, much appreciated!

**Comment by legshort** [comment]
@etiology thanks for the well-explained answer.
However, there is `Profile` Faker provider [link](http://faker.readthedocs.io/en/master/providers/faker.providers.profile.html) and there is `username` field inside of `Profile`.

It looks like `Profile` is a `dict` not like other Faker Provider, that's why I'm having a trouble to extract the nested field from it.

**Comment by jeffwidman** [comment]
Re-opening so this doesn't get lost, although I don't have time to look into this right now.

**Comment by etiology** [comment]
Well I have a not super great solution.  It adds an extra call so maybe someone can clean it up:

```python
import factory
from faker import Faker

fake = Faker()

def generate_username(*args):
    """ returns a random username """
    return fake.profile(fields=['username'])['username']

class Profile(object):
    """ Simple Profile model """
    def __init__(self, **kwargs):
        self.username = kwargs.get('username')

class ProfileFactory(factory.Factory):
    """ Generate random profile instances """
    class Meta:
        model = Profile
    username = factory.LazyAttribute(generate_username)

```

Test
```python
for x in range(10):
    a = ProfileFactory()
    print(a.username)
```

Output:
```bash
reeselinda
arroyozachary
gonzalescatherine
xcarpenter
jcohen
zsimmons
stokestyler
ofletcher
monicaphelps
johnharris
```

**Comment by legshort** [comment]
Yeah, I was looking for the elegant way to fake information, also I had the same problem with generating same random value with `Faker` instance directly instead of using `factory.Faker()`.

Therefore, I prefer to use `factory.Faker()`. I guess I have to deal with `LazyAttribute` so far.

If anyone has a better way to do it please share here for us, thanks!

**Comment by rbarrois** [comment]
It's a bit hidden, but Faker has a ``user_name`` provider: http://faker.readthedocs.io/en/latest/providers/faker.providers.internet.html?highlight=user_name

=> You can use ``factory.Faker('user_name')`` ;)

**Comment by legshort** [comment]
well, it seems like `providers.profile` is a combination of others.
Thanks for the tip!

**Comment by gotexis** [comment]
factory.Faker('user_name')

Not working as of 2019

Could some1 else try? I have to use  @etiology 's not-elegant solution now.

**Comment by rbarrois** [comment]
@gotexis works perfectly here:
```python
>>> import factory
>>> factory.build(dict, user=factory.Faker('user_name'))
{'user': 'rebecca96'}
```

**Comment by jonjonw** [comment]
I just wanted to pass along my solution to a similar challenge with `factory.Faker('currency')`. It also returns a tuple with a currency code and currency name like `('USD', 'United States Dollar')`.

It also has alternative calls for `Faker('currency_code')` and `Faker('currency_name')` but using them for the same object gives inconsistent values like `('GBP', 'Mexican Paso')`. After a lot of searching, I discovered the `exclude` property on the factory metaclass and set it up this way:

```py
class AssetFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = 'bank.Asset'
        exclude = ('currency_code_name',)

    currency_code_name = factory.Faker('currency') # excluded
    code = factory.LazyAttribute(lambda o: o.currency_code_name[0]),
    name = factory.LazyAttribute(lambda o: o.currency_code_name[1]),
```

I was also pleased to discover that it can be tucked away in a trait if it's only used there:
```py
class AssetFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = 'bank.Asset'
        exclude = ('currency_code_name',)

    class Params:
        currency = factory.Trait(
            currency_code_name = factory.Faker('currency'), # excluded
            symbol = factory.LazyAttribute(lambda o: o.currency_code_name[0]),
            name = factory.LazyAttribute(lambda o: o.currency_code_name[1]),

    symbol = factory.Faker('text')
    name = factory.LazyAttribute(
        lambda _: f'{factory.Faker("company")}, {factory.Faker("company_suffix")}'
    )
```
It would be nice if this was documented in a more obvious place.

**Comment by rbarrois** [comment]
@jonjonw Indeed, the docs could use a more expanded "recipes" section ;)

For your use case, it's now even simpler with `class Params`:

```python
class AssetFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = 'bank.Asset'

    class Params:
        currency_code_name = factory.Faker('currency')

    currency_symbol = factory.LazyAttribute(lambda o: o.currency_code_name[0])
    currency_name = factory.LazyAttribute(lambda o: o.currency_code_name[1])
    symbol = factory.Faker('text')
    name = factory.LazyAttribute(
        lambda _: f'{factory.Faker("company")}, {factory.Faker("company_suffix")}'
    )
```
