### ISSUE TITLE
factory.Faker does not respect max_length of django model fields

### ISSUE THREAD

**Issue by Alireza2n** [FactoryBoy/factory_boy#427]
Hi,
First of all, great job on the whole project, I'm really grateful.

I am using `factory.Faker`, but I get numerous errors on exceeding `max_length` of field:

> django.db.utils.DataError: value too long for type character varying

such problem does not exist with `factory.fuzzy.FuzzyText` as it accepts a `length` argument.

I think we should add `length` as an argument to `factory.Faker` or maybe force it to respect max_length in django's models.

Here are some exerts of my code:
**Model**
`class InsuranceTypes(models.Model):`
`    type_name = models.CharField(max_length=50, verbose_name=_('type_name'), unique=True)`

**Factory**
`class InsuranceTypesFactory(factory.django.DjangoModelFactory):`
`    class Meta:`
`        model = InsuranceTypes`
`    type_name = factory.Faker('word')`

**Comment by stephenross** [comment]
One thing you could use would be to use one of the other text based outputs, as several of the text providers allow defining character limits such as pystr. There does need to be an update pass on Faker to provide a max length on most of the fields and make the naming convention the same across all providers, but that will be a change to Faker code and not factory_boy.

**Comment by Alireza2n** [comment]
Since this issue required change to Faker, I will close the issue.

**Comment by Alireza2n** [comment]
Since this issue requires change to Faker, I will close the issue.
