### ISSUE TITLE
Reference to sub app model field with string notation

### ISSUE THREAD

**Issue by mainstream95** [FactoryBoy/factory_boy#440]
There is no support for model field with string notation possibly.
It only saw first part of dot as app and 'subapp.model' as model
I think this is strange because of wrong parse and message like 'subapp.model'  doesn't exist,  although we can parse whole model i.e.  with location method or etc . 

    class Meta:
        model = 'app.subapp.Model'

**Comment by rbarrois** [comment]
Hi,

On which ORM do you notice this issue? Can you give us an example of the wrong parse/message?

**Comment by rbarrois** [comment]
Hi! I'm closing this issue for now, in order to keep the list somewhat manageable.

But please reopen it if you've still got the bug — with a full traceback hopefully!
