### ISSUE TITLE
calling reset() on a fresh Iterator causes exception

### ISSUE THREAD

**Issue by rrauenza** [FactoryBoy/factory_boy#443]
```
  File ".../virtualenv-2.7.5/lib/python2.7/site-packages/factory/declarations.py", line 186, in reset
    self.iterator.reset()
AttributeError: 'NoneType' object has no attribute 'reset'
```
This is of course because we haven't used the iterator yet!  But in my use case, I have a factory that I want to reset the iterator at the top of a loop ... (Ok, I could move it to the bottom instead)

What do you think of just adding ```if self.iterator``` above the call?

**Comment by rbarrois** [comment]
That's a great idea — or a good bugfix, depending on your point of view ;)

I'll merge it right away.

**Comment by rrauenza** [comment]
Thanks!  And thanks for the package -- it makes TDD so much easier!!
