### ISSUE TITLE
Django FileField throws "fixture 'dict' not found"

### ISSUE THREAD

**Issue by dabdada** [FactoryBoy/factory_boy#449]
We have a testsetup with:
* python 2.7
* django 1.8.18
* pytest == 3.4.0
* pytest-factoryboy == 2.0.0
* factoryboy == 2.10.0

When using factory.django.FileField as a SubFactory for an attribute for one of our Django Models and want to execute a test using the LazyFixture, We get an Error "fixture 'dict' not found".

When installing pytest-factoryboy 1.3.2 and factoryboy 2.8.1 the tests do run successfully.

The change we observed so far is that the declarations for the django.FileField changed from "declarations.ParameteredAttribute" to "declarations.Dict" (Which seems to be related somehow).

Unfortunatelly I was not able to investigate any further. If you need some more information please do not hasitate. I am glad to provide them as fast as possible.

**Comment by rbarrois** [comment]
Hi,

The error message and the ``LazyFixture`` object aren't part of the factory_boy code base, so I think the issue comes from pytest-factoryboy.
However, this seems to be the same issue as #451, opened by pytest-factoryboy's author; I'll follow up there.

Thanks for the report ;)
