### ISSUE TITLE
Better support for copying fields to sub factory - expose _Resolver__declarations.contexts

### ISSUE THREAD

**Issue by samuelcolvin** [FactoryBoy/factory_boy#455]
The solutions given in [the docs on copying fields to a subfactory](http://factoryboy.readthedocs.io/en/latest/recipes.html#copying-fields-to-a-subfactory) don't work properly.

Take the following factory:

```py
# students and clients both have a "user" field, students and clients should always share
# the same company defined at user.company
import factory.django
from models import Student
from factories import UserFactory, ClientFactory

gen_user = factory.LazyAttribute(lambda o: UserFactory(company=o.factory_parent.user.company))


class StudentFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Student

    user = factory.SubFactory(UserFactory)
    # client = factory.SubFactory(ClientFactory, user=gen_user)

    @factory.lazy_attribute
    def client(self):
        kwargs = dict(user__company=self.user.company)
        kwargs.update(self._Resolver__declarations.contexts.get('client', {}))
        return ClientFactory(**kwargs)
```

The commented out solution `# client = factory.SubFactory(ClientFactory, user=gen_user)` doesn't work because if I define `StudentFactory(client__age=10, client__user__name='foobar')` `client.age` is honored but `client.user.name` is ignored.

The second solution with a `lazy_attribute` works but is ugly and wasn't easy to find.

`self._Resolver__declarations.contexts` should be exposed in a more user friendly variable and documented.

**Comment by tysonclugg** [comment]
It's annoying that RelatedFactory supports chained attributes (eg: `StudentFactory(client__age=10)`), but SubFactory doesn't.  Can the chained attribute behaviour from RelatedFactory be ported to SubFactory?

**Comment by tysonclugg** [comment]
I scratched together the following code that builds on the lazy_attribute solution presented by @samuelcolvin:
```python
# students and clients both have a "user" field, students and clients should always share
# the same company defined at user.company
import six
import factory.django
from models import Student
from factories import UserFactory, ClientFactory

gen_user = factory.LazyAttribute(lambda o: UserFactory(company=o.factory_parent.user.company))


class ChainedSubFactoryMeta(factory.base.FactoryMetaClass):
    def __new__(cls, name, bases, attrs):
        for name, attr in attrs.items():
            if isinstance(attr, factory.SubFactory):
                attrs[name] = factory.lazy_attribute(
                    lambda self, _name=name, _sub_factory=attr.get_factory(): _sub_factory(
                        **self._Resolver__declarations.contexts.get(name, {})
                    )
                )
        return super(ChainedSubFactoryMeta, cls).__new__(cls, name, bases, attrs)


class ChainedDjangoModelFactory(six.with_metaclass(ChainedSubFactoryMeta, factory.DjangoModelFactory)):
    pass


class StudentFactory(ChainedDjangoModelFactory):
    class Meta:
        model = Student

    user = factory.SubFactory(UserFactory)
    client = factory.SubFactory(ClientFactory, user=gen_user)
```

Perhaps something like this could be used as the basis for a PR.

**Comment by rbarrois** [comment]
@samuelcolvin As stated in the docs, the expected declaration for relying on other fields would be:

```python
# students and clients both have a "user" field, students and clients should always share
# the same company defined at user.company
import factory.django
from models import Student
from factories import UserFactory, ClientFactory

gen_user = factory.LazyAttribute(lambda o: UserFactory(company=o.factory_parent.user.company))


class StudentFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Student

    user = factory.SubFactory(UserFactory)
    client = factory.SubFactory(
        ClientFactory,
        # Using '...user' : '.' for the UserFactory, '..' for the ClientFactory, '...' for the StudentFactory
        user=factory.SubFactory(UserFactory, company=factory.SelfAttribute('...user.company')),
    )
```

It looks like the docs could be improved; I think the word *indirectly* in the sentence isn't clear enough (*If the value of a field on the child factory is **indirectly** derived from a field on the parent factory*) - in your case, the client's user's company is **directly** copied from the student's user's company.

Could you try that and tell me whether this fixes the issue you're having?

**Comment by rbarrois** [comment]
@tysonclugg It looks like what you're describing is unrelated to the initial topic; could you open a separate issue describing your specific problem?

As far as I know, you definitely can use a chained attribute in a ``SubFactory`` — it would be pretty useless it didn't :wink:

**Comment by samuelcolvin** [comment]
Thanks, that fixed it. Sorry about the noise.
