### ISSUE TITLE
Create a FuzzyTime attribute

### ISSUE THREAD

**Issue by YPCrumble** [FactoryBoy/factory_boy#458]
Would the maintainers be interested in a FuzzyTime attribute for FactoryBoy? I'm thinking something like 

    FuzzyTime([lower_bound_time], [upper_bound_time])

...where both bounds are optional. Or is there a way to achieve this with the current FactoryBoy implementation? Happy to create a PR if that's helpful. Thanks for maintaining this repo!

**Comment by Tecktron** [comment]
As per [the docs](http://factoryboy.readthedocs.io/en/latest/fuzzy.html), the Fuzzy attributes are being phased out. You can (and should) use Faker to accomplish this. Here's an example:
`timestamp = factory.Faker('date_time_between', start_date='-30d', end_date='now', tzinfo=None)`

http://factoryboy.readthedocs.io/en/latest/reference.html#faker
https://faker.readthedocs.io/en/latest/providers/faker.providers.date_time.html
