### ISSUE TITLE
Document new Managing randomness

### ISSUE THREAD

**Issue by chimeno** [FactoryBoy/factory_boy#459]
It seems Managing randomness it's outdated: https://factoryboy.readthedocs.io/en/latest/fuzzy.html#managing-randomness, since the module now lives in ``factory.random``

Also an example of how to get the state and insert them later would be useful.

**Comment by stefan6419846** [comment]
Is this still an issue? It seems like the documentation has been changed since then, while documenting `get_random_state` and `set_random_state` as well: https://factoryboy.readthedocs.io/en/latest/reference.html#randomness-management
