### ISSUE TITLE
Factory_boy without an ORM

### ISSUE THREAD

**Issue by vogxn** [FactoryBoy/factory_boy#46]
This is more a question than an issue since I didn't find a mailing list where I could ask this question. Apologize if this isn't the place to ask.

I'm trying to use factory_boy without an ORM or Django. I've no experience in either. 

So I've got a library in python which is used as a test framework. Over time the test data that was managed using dictionaries has grown in size that it has become unweildy to manage. Much of this test data needs to be passed to my functional tests. So, I decided to use factory_boy for defining this test-data as a representation of factory_boy managed objects.

My object model is similar to the examples shown in factory_boy's wiki page:

AccountFactory (inherit) AdminAccountFactory (inherit) UserAccountFactory 

Similarly
NetworkFactory (inherit) IsolatedNetworkFactory (inherit) SharedNetworkFactory and so on...

 So my questions are as follows

a) Is factory_boy the right tool for addressing this problem?
b) If yes, can it be used without dependency on Django, Mojo and/or any ORM?
c) If no, what (to your knowledge) would best solve my test management problem?

Thanks in advance,

**Comment by jayusa123** [comment]
For anyone who comes across this, I'm using FactoryBoy 2.12.0 and can generate non-model objects with no additional setup. Since I'm using `NamedTuple` I don't have to manually handle the parameters passed to the class during initialization. 

```python
from typing import NamedTuple
import factory


class TestUser(NamedTuple):
    id: int
    name: str


class TestUserFactory(factory.Factory):
    class Meta:
        model = TestUser

    id = factory.Sequence(lambda n: 1000 + n)
    name = factory.Faker('name')

```
``` python
>>> TestUserFactory.create_batch(5)
[TestUser(id=1000, name='Roger Garcia'),
 TestUser(id=1001, name='Shannon Williams'),
 TestUser(id=1002, name='Rachel Clark'),
 TestUser(id=1003, name='Peter Phillips'),
 TestUser(id=1004, name='Marisa Hicks')]

**Comment by HoshiYamazaki** [comment]
> For anyone who comes across this, I'm using FactoryBoy 2.12.0 and can generate non-model objects with no additional setup. Since I'm using `NamedTuple` I don't have to manually handle the parameters passed to the class during initialization.
> 
> ```python
> from typing import NamedTuple
> import factory
> 
> 
> class TestUser(NamedTuple):
>     id: int
>     name: str
> 
> 
> class TestUserFactory(factory.Factory):
>     class Meta:
>         model = TestUser
> 
>     id = factory.Sequence(lambda n: 1000 + n)
>     name = factory.Faker('name')
> ```
> 
> ```python
> >>> TestUserFactory.create_batch(5)
> [TestUser(id=1000, name='Roger Garcia'),
>  TestUser(id=1001, name='Shannon Williams'),
>  TestUser(id=1002, name='Rachel Clark'),
>  TestUser(id=1003, name='Peter Phillips'),
>  TestUser(id=1004, name='Marisa Hicks')]
> ```

It's possible to just not define tuple? I tried to use by model parameter an `object` but this seems not to work, same about `mock.Mock()` or `mock.Mock` (yep, I'm crazy enough to try to use mock to create virtual object with parameters... sometimes).

I just want to define them once, at initialization lvl, without defining tuple struct.

**Comment by marquicus** [comment]
factory class simplified

```
class TestUserFactory(factory.Factory):
    id = factory.Sequence(lambda n: 1000 + n)
    name = factory.Faker('name')

    class Meta:
        model = NamedTuple("TestUser", [('id', int), ('name', str)])

```

**Comment by wolf-mx** [comment]
Getting following error in this case:
`AttributeError: 'Component' object has no attribute 'build'`. Using factory_boy==3.1.0 and Python 3.8.

> factory class simplified
> 
> ```
> class TestUserFactory(factory.Factory):
>     id = factory.Sequence(lambda n: 1000 + n)
>     name = factory.Faker('name')
> 
>     class Meta:
>         model = NamedTuple("TestUser", [('id', int), ('name', str)])
> ```

**Comment by rbarrois** [comment]
@wolf-mx It must be another error in your code, running the code above with the versions you mention works perfectly fine ;)

Feel free to open a dedicated issue if you can reproduce the bug you're seeing!

**Comment by wolf-mx** [comment]
> @wolf-mx It must be another error in your code, running the code above with the versions you mention works perfectly fine ;)
> 
> Feel free to open a dedicated issue if you can reproduce the bug you're seeing!

its basically almost 1:1 code snippet from above. I am just initiating it `TestUserFactory().build()`. And here it happens. Or is there another way to create the object?

**Comment by rbarrois** [comment]
@wolf-mx `TestUserFactory()` is an alias for `TestUserFactory.build()`, don't use both ;)

So, replace your call with either `TestUserFactory()` or `TestUserFactoroy.build()`!

**Comment by wolf-mx** [comment]
> @wolf-mx `TestUserFactory()` is an alias for `TestUserFactory.build()`, don't use both ;)
> 
> So, replace your call with either `TestUserFactory()` or `TestUserFactoroy.build()`!

Ouch! That one hurts. Works now - thanks a lot.

**Comment by Zlira** [comment]
> For anyone who comes across this, I'm using FactoryBoy 2.12.0 and can generate non-model objects with no additional setup. Since I'm using `NamedTuple` I don't have to manually handle the parameters passed to the class during initialization.
> 
> ```python
> from typing import NamedTuple
> import factory
> 
> 
> class TestUser(NamedTuple):
>     id: int
>     name: str
> 
> 
> class TestUserFactory(factory.Factory):
>     class Meta:
>         model = TestUser
> 
>     id = factory.Sequence(lambda n: 1000 + n)
>     name = factory.Faker('name')
> ```
> 
> ```python
> >>> TestUserFactory.create_batch(5)
> [TestUser(id=1000, name='Roger Garcia'),
>  TestUser(id=1001, name='Shannon Williams'),
>  TestUser(id=1002, name='Rachel Clark'),
>  TestUser(id=1003, name='Peter Phillips'),
>  TestUser(id=1004, name='Marisa Hicks')]
> ```

Or, if you don't want to define the set of fields twice, and don't want to use `unittests.mock.Mock` because of its other behaviours, you can use `types.SimpleNamespace` as a model.
```python
import factory
from types import SimpleNamespace

class TestUserFactory(factory.Factory):
    class Meta:
        model = SimpleNamespace

    id = factory.Sequence(lambda n: 1000 + n)
    name = factory.Faker('name')

```
```
