### ISSUE TITLE
[question] How to generate random values........................................

### ISSUE THREAD

**Issue by seospace** [FactoryBoy/factory_boy#464]
I need random emails, like:

'Aksoas9a8sd9aASDkasdas9@azxclkasoiASDASd908s.Com'

I cant find in docs how factoryboy can help me.
Question is, i am stupid?

**Comment by Tecktron** [comment]
Use the Faker declaration:
`email = factory.Faker('email')`

https://factoryboy.readthedocs.io/en/latest/reference.html#faker
https://faker.readthedocs.io/en/latest/providers/faker.providers.internet.html

**Comment by rbarrois** [comment]
Glad to see you found an answer :)

I'm closing the issue for now; but it looks like the docs aren't quite straightforward on those questions. Could you tell us where you looked when trying to find this piece of information? I'll try to improve that section first :)

**Comment by Tecktron** [comment]
@rbarrois I just read the docs, but all the docs. I'll put something together for the intro section on using the Faker class and make a PR for you.
