### ISSUE TITLE
Model returned from .create() doesn't have an id

### ISSUE THREAD

**Issue by darthdeus** [FactoryBoy/factory_boy#465]
I might be missing something, but the docs say that `create()` returns a saved model, but if I simply do `UserFactory.create().id` I get back `None`, yet if I do `user = UserFactory.create(); user.save()` then the `user.id` is actually set.

**Comment by marcosschroh** [comment]
The have same problem. I am working with Django 1.11.8 and Python 2.7

**Comment by marcosschroh** [comment]
@darthdeus I realized that I need to inheritance from factory.django.DjangoModelFactory (In the case of Django). After that it works.

**Comment by rbarrois** [comment]
Indeed — the first versions where built for Django, but the library has evolved to cover a much broader style of Python libraries.

You'll have to use the specific subclass for your framework — which also brings a few extra options, too!

I'm closing this issue, but please reopen it / submit some improvements to the doc where you would have expected to find that information!
