### ISSUE TITLE
Add support for Django unique_together

### ISSUE THREAD

**Issue by broxeph** [FactoryBoy/factory_boy#487]
`DjangoModelFactory._get_or_create()` doesn't appear to have any support for the `unique_together` attribute of `Model.Meta`. Perhaps it'd be a good idea to allow `unique_together` tuples in `DjangoModelFactory.Meta.django_get_or_create`?

I'll attach a PR to illustrate a potential approach. Can modify/add tests as necessary.

Thanks!

**Comment by rbarrois** [comment]
Can you explain the type of error you have?

Unless I'm mistaken, you can do:

```python
class Membership(models.Model):
    class Meta:
        unique_together = [('user', 'team')]
    user = models.ForeignKey(User)
    team = models.ForeignKey(Team)
    level = models.CharField(choices=LEVEL_CHOICES, default=LEVEL_MEMBER)

class MembershipFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Membership
        django_get_or_create = ['user', 'team']

    user = factory.SubFactory(UserFactory)
    tean = factory.SubFactory(TeamFactory)
    level = models.Membership.LEVEL_MEMBER
```

Here, any ``MembershipFactory`` will call ``Membership.objects.get_or_create(user=user, team=team, defaults={'level': level})``

**Comment by broxeph** [comment]
Sure, but multiple unique constraints, e.g. `[('user', 'team'), ('user', 'level')]`, raise the question of how to approach `django_get_or_create`—`['user', 'team', 'level']` will call `Membership.objects.get_or_create(user=user, team=team, level=level)`, which may attempt to create instances with unique user/team/level combinations, but occasionally duplicate user/team or user/level combinations.

**Comment by rbarrois** [comment]
Yes. But, in my opinion, that's something that the person who has full domain knowledge must take; the library cannot take a relevant "best" guess here.

Note that you can override the ``_create()`` method to add your own logic :)
