### ISSUE TITLE
Allow Renamed Keyword Arguments to be Optional

### ISSUE THREAD

**Issue by mrname** [FactoryBoy/factory_boy#504]
#### The problem
When using the `rename` functionality to rename a keyword argument, an error is thrown if the keyword argument is not passed into the factory. For example, given a class with a field called `total_score` and adding `rename = {'score': 'total_score'}` will throw the following exception if `score` is not passed into the factory.

```
    @classmethod
    def _rename_fields(cls, **kwargs):
        for old_name, new_name in cls._meta.rename.items():
>           kwargs[new_name] = kwargs.pop(old_name)
E           KeyError: 'score'
```

#### Proposed solution
Allow the model instance to be created if the keyword argument is not present, essentially just ignoring the keyword conversion.

**Comment by rbarrois** [comment]
Hi!

That sounds useful indeed; would you be able to craft a PR for that feature?
I think we just need to change that function to skip the assignment when ``old_name not in kwargs``; and, obviously, add a couple of tests and adjust the docs ;)

**Comment by mrname** [comment]
@rbarrois happy to take care of it! I am traveling right now but will try to get a PR done by the weekend. Thanks!

**Comment by federicobond** [comment]
Fixed in https://github.com/FactoryBoy/factory_boy/commit/ae780a38c2311cf6d306797889f09db4d395a6d4
