### ISSUE TITLE
Documentation: changelog does not show when Django versions <1.7 support was dropped

### ISSUE THREAD

**Issue by anentropic** [FactoryBoy/factory_boy#514]
#### The problem
Project is on old Django version. Upgraded to latest factory_boy. Tests broke in very obscure way due to error at import time.

In my case the error looked like:
```
  File "/Dev/myproject/VENV/lib/python2.7/site-packages/flaky/flaky_nose_plugin.py", line 110, in afterTest
    if self._test_status[test]:
KeyError: Test(<myproject.tests.MyTestCase testMethod=test_something>)
```
Possibly the `flaky` plugin is also at fault for masking the traceback. The real traceback was `ImportError('cannot import name apps',)` coming from:
https://github.com/FactoryBoy/factory_boy/blob/2.11.1/factory/django.py#L62

#### Proposed solution
If it's possible to manually edit the changelog file in the docs... the changelog for v2.9.0 should note that Django < 1.7 are no longer supported
https://factoryboy.readthedocs.io/en/latest/changelog.html#v2-9-0

**Comment by jeffwidman** [comment]
Sorry about this!

Afraid I don't remember whether the changelog is autogenerated or not... I think it's manually edited, but @rbarrois can you confirm?

**Comment by francoisfreitag** [comment]
With https://github.com/FactoryBoy/factory_boy/pull/601, supported Django versions should be mentioned in the README.
