### ISSUE TITLE
Strange behaviour with SQLAlchemy

### ISSUE THREAD

**Issue by leamingrad** [FactoryBoy/factory_boy#516]
#### The problem
I am currently trying to create factories for SQLAlchemy models, one of which takes a parameter that specifies the length of a list of the other one.

In order to achieve this, I have extended `LazyAttribute` as suggested in https://github.com/FactoryBoy/factory_boy/issues/51, so that the new `LazyAttributeWithStrategy` is passed the creation strategy as well as the instance. I then build or create the list of child models with the following:

```
    @lazy_attribute_with_strategy
    def books(self, strategy):
        if strategy == factory.BUILD_STRATEGY:
            return [
                BookFactory.build(author=self)
                for _ in range(self.num_books)
            ]
        elif strategy == factory.CREATE_STRATEGY:
            return [
                BookFactory.create(author=self)
                for _ in range(self.num_books)
            ]
```

Here `num_books` is a parameter on the factory. This works fine when using the build strategy, but when I use the create strategy it crashes with:

```
AttributeError: The parameter '_sa_instance_state' is unknown. Evaluated attributes are {'name': 'safe', 'num_books': 10}, definitions are <DeclarationSet: {'name': <factory.faker.Faker object at 0x7fa768efa978>, 'books': <__main__.LazyAttributeWithStrategy object at 0x7fa768efaa20>, 'num_books': 10}>.
```

The attached `test_script.txt` can be run as a reproduction of the issue.

[test_script.txt](https://github.com/FactoryBoy/factory_boy/files/2374858/test_script.txt)

#### Proposed solution
I'm not sure what the solution is here - but maybe the `SQLAlchemyModelFactory` needs to handle `_sa_instance_state` in some special way.

#### Extra notes
To be honest, I am not convinced that a custom version of `LazyAttribute` is the best way to achieve what I actually want - the ability for a factory to take a parameter that sets the length of a list of child factories.

Other ways I have tried:
* Use a normal `LazyAttribute` with a `SubFactory` - this allows me to get the length parameter, but I cannot use `factory.SubFactory` inside the `LazyAttribute`
* Use `factory.List` with a `SubFactory` - this allows me to generate the children correctly, but I could not find a way of accessing the length attribute in a way that would let me pass it to `range`, and the same issue with `_sa_instance_state` is also hit
* Use a normal `LazyAttribute` with direct child instantiation - this allows me to get the length parameter, but the factory tries to add things to the database even if it isn't needed

Is there a way to do this that I have missed?

**Comment by jeffwidman** [comment]
What are the model definitions? Are the FK's loaded lazily or eagerly? http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html

**Comment by leamingrad** [comment]
In the production code this came from the relationships are eager-loaded (`lazy='joined'`) but in the attached example they are dynamically loaded

**Comment by federicobond** [comment]
This should now be possible with the recently merged https://github.com/FactoryBoy/factory_boy/commit/d74b4ff65f78fbd14de5b576bfe30392b8ab799f. (unpublished).

Let me know if it works for you and feel free to reopen this issue if it doesn't.
