### ISSUE TITLE
Flake8 Binary Operators Lint Fix

### ISSUE THREAD

**Issue by mattmahowald** [FactoryBoy/factory_boy#547]
#### Description
Travis is failing for Python3.7 because the flake8 spec does not have a decision regarding where to break lines around binary operators.

#### To Reproduce
This occurs in all current builds

##### Model / Factory code
Flake8 produces this failure `W504: line break after binary operator` on this code block in `utils.py`
```python
    def __str__(self):
        return ', '.join(
            [_safe_repr(arg) for arg in self.args] +  # violation here
            [
                '%s=%s' % (key, _safe_repr(value))
                for key, value in self.kwargs.items()
            ]
        )
```

#### Suggestion for fixing
The easiest fix is to additionally disable `W504` in linting, which allows line breaking after binary operators. However, this is the superior method of line breaking.

**Comment by rbarrois** [comment]
Thanks for the report! This has been fixed.
