### ISSUE TITLE
Release 2.11.2?

### ISSUE THREAD

**Issue by aerostitch** [FactoryBoy/factory_boy#552]
Hi guys,

I would really love to see a tagged release of factory_boy with an official Python 3.7 and Django 2.1 support. Do you know when you are planning to do the release 2.11.2?

Thanks for your help,
Joseph

**Comment by francoisfreitag** [comment]
[2.12.0](https://github.com/FactoryBoy/factory_boy/releases/tag/2.12.0) was released May 11th.
