### ISSUE TITLE
`create` or `created`?

### ISSUE THREAD

**Issue by uri-rodberg** [FactoryBoy/factory_boy#557]
#### The problem
*Please describe the problem you're encountering (e.g "It's very complex to do [...]")*

In https://factoryboy.readthedocs.io/en/latest/reference.html it says:

`A decorator is also provided, decorating a single method accepting the same obj, created, extracted and keyword arguments as PostGeneration.`

But the positional arguments given there are `self, create, extracted, **kwargs`

#### Proposed solution
*Please provide some wild idea you think could solve this issue. It's much easier to work from an existing suggestion :)*

I think it should be either `created` or `create`.

#### Extra notes
*Any notes you feel interesting to include: alternatives you've considered, reasons to include the change, anything!*

**Comment by evgenymozhaev** [comment]
I'd love to fix it. I'm new to opensource, so I will try to get it done by the weekend.

**Comment by uri-rodberg** [comment]
@evgenymozhaev Thank you. It seems to me that `created` is correct but I'm not sure.

**Comment by evgenymozhaev** [comment]
@uri-rodberg I believe `create` is more appropriate here, because it is `create` parameter everywhere in the code.

**Comment by uri-rodberg** [comment]
@evgenymozhaev I think it depends on the meaning of the variable and what it represents. If I'm correct, it's a boolean variable that is true if the object was created. It appears in the `post_generation` functions after the object was created. But I'm not sure.

**Comment by evgenymozhaev** [comment]
@uri-rodberg yes, but on the other hand they say that it `is a boolean indicating which strategy was used`. One can say that the strategy "create" was used. I'm not sure, but I think it is better to change the docs and leave the parameter name the same as in other functions.

**Comment by federicobond** [comment]
I believe this is fixed. Both the code and docs now use `create` consistently.
