### ISSUE TITLE
'Options' object has no attribute 'pre_declarations' is too ambiguous

### ISSUE THREAD

**Issue by claysauruswrecks** [FactoryBoy/factory_boy#561]
#### The problem
Typo incorrectly specifying the Model for a Factory.

#### Proposed solution
Check if any specified factories are actually Models, in which case give a more clear error message.

#### Extra notes
Thanks for the good work on this neat lib!

**Comment by rbarrois** [comment]
Hi!
Can you give an example of the typo that caused the error?
It's a bit difficult to enforce the parent class of a factory's ``class Meta: model = Foo`` — I want the library to be able to create any kind of objects...

**Comment by david-wolgemuth** [comment]
Here's an example of a typo that caused the error for me:

##### `/common/factories/product.py`

```python
import factory
from common.models.product import Product

class ProductFactory(factory.DjangoModelFactory):
    class Meta:
        model = Product

    category = factory.SubFactory('common.factories.category.Category')
   # should be `common.factories.category.CategoryFactory` (the factory, not the model)
```

##### `/common/factories/category.py`

```python
import factory
from common.models.category import Category

class CategoryFactory(factory.DjangoModelFactory):
    class Meta:
        model = Category
```

**Comment by claysauruswrecks** [comment]
Exactly :smiley: 

I propose catching this specific error, and giving an error which is more clearly actionable, thereby improving developer UX, something like: "Model is defined inside SubFactory, did you mean to use ModelFactory instead?".

**Comment by Jasper-Koops** [comment]
Just ran into this error as well - this topic helped me to debug / solve the problem. A different error message might help future users

**Comment by jonathan-s** [comment]
Same here, a clearer error message would certainly help.

**Comment by TaipanRex** [comment]
Same here

**Comment by atleta** [comment]
Meh, I keep forgetting what this error means, though I have figured it out several times. :-/

**Comment by polinom** [comment]
I could  spend hours debuting this if I did not find this issue on github.

**Comment by FractalWire** [comment]
I think this is also an issue for RelatedFactory:

```
    pro_info = factory.Maybe('professional', factory.RelatedFactory(ProInfo))
...
    AttributeError: 'Options' object has no attribute 'pre_declarations'
```
When it should be `ProInfoFactory` here
