### ISSUE TITLE
Request: add 'how to seed' to the readme.md

### ISSUE THREAD

**Issue by Pomax** [FactoryBoy/factory_boy#563]
The readme.md currently reads:
>Note
>
>Use of fully randomized data in tests is quickly a problem for reproducing broken builds. To that purpose, factory_boy provides helpers to handle the random seeds it uses.

however, that is the only mention of the word "seed" in the entire readme, could a bit be added that shows how to actually seed a Faker so multiple runs with the same see yield the same data?

**Comment by rbarrois** [comment]
Hi,

The readme aims to provide a quick overview of the available features; the detailed versions should be in the docs.
However, it's true that this pointer is very minimal, and the docs section is lacking as well.

If you could tell me the kind of informations you'd have expected on the README & docs, I'll try to add them :)

**Comment by Pomax** [comment]
random seeding is super important, so I'd absolutely include that in a quick overview. A small section below "Realistic, random values:" would be all that's necessary on the readme side:

```
Realistic, random values
""""""""""""""""""""""""

  ......

Realistic pseudo-random values
""""""""""""""""""""""""""""""

When deterministic, pseudo-random values are required, factory_boy can be seeded with a fixed integer value in the range (...whatever range is accepted...):

.. code-block:: python

    import os
    import factory

    factory.Faker.seed(os.environ['SEED_VALUE'])
    
.. note:: for universal pseudo-random values, you may want to seed python's random number generator instead, using [random.seed](https://docs.python.org/3/library/random.html#random.seed)
```

**Comment by rbarrois** [comment]
And that's done!

Thanks for the suggestions too, it allowed me to notice that the docs weren't pointing to the right methods...

**Comment by rbarrois** [comment]
@Pomax FYI, the docs are available here:
- https://factoryboy.readthedocs.io/en/latest/recipes.html#using-reproducible-randomness for the recipe
- https://factoryboy.readthedocs.io/en/latest/reference.html#randomness-management for the reference section

**Comment by Pomax** [comment]
awesome, thanks so much!
