### ISSUE TITLE
Iterator laziness doesn't seem to work with sqlalchemy 

### ISSUE THREAD

**Issue by antgel** [FactoryBoy/factory_boy#564]
#### Description
According to [the docs](https://factoryboy.readthedocs.io/en/latest/recipes.html#choosing-from-a-populated-table):

> Here, models.Language.objects.all() won’t be evaluated until the first call to UserFactory; thus avoiding DB queries at import time.

I'm not using Django, rather sqlachemy (or more precisely, [flask-sqlalchemy](http://flask-sqlalchemy.pocoo.org/2.3/). I'm trying to do something similar and it fails.

#### To Reproduce
See below, noting use of `factory.Iterator(User.query.all())`.

##### Model / Factory code
```python
import factory
from myapp.extensions import db
from myapp.resources.user import User, UserFactory

class Incident(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    reporting_user_id = db.Column(db.Integer,
                                  db.ForeignKey('user.id'),
                                  nullable=False)
    reporting_user = db.relationship('User', backref='incidents')

# IncidentSchema deleted for brevity

class IncidentFactory(factory.alchemy.SQLAlchemyModelFactory):
    class Meta:
        model = Incident
        sqlalchemy_session = db.session

    reporting_user = factory.Iterator(User.query.all())

# IncidentView deleted for brevity
```

##### The issue

```python
Traceback (most recent call last):
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1014, in __call__
    return self.registry[key]
KeyError: 140173732824896

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myapp.py", line 1, in <module>
    from myapp.app import create_app
  File "/home/antony/src/git/myapp/myapp/app.py", line 4, in <module>
    from myapp.resources.incident import IncidentsView
  File "/home/antony/src/git/myapp/myapp/resources/incident.py", line 31, in <module>
    class IncidentFactory(factory.alchemy.SQLAlchemyModelFactory):
  File "/home/antony/src/git/myapp/myapp/resources/incident.py", line 38, in IncidentFactory
    reporting_user = factory.Iterator(User.query.all())
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 515, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1016, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3169, in __call__
    return self.class_(**local_kw)
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 142, in __init__
    self.app = app = db.get_app()
  File "/home/antony/.virtualenvs/myapp/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 913, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```

#### Notes

In the above example, I don't even import `IncidentFactory`, yet the `User.query.all()` is still executed. Perhaps I've misunderstood the docs, but "won’t be evaluated until the first call" seems pretty clear.

**Comment by etiology** [comment]
Your factory doesn't need to define your relationship value.  SQLAlchemy will do that for you via the relationship attribute.  You may want to generate users when you create this factory but that's it.

You only need to generate the foreign key to a model.  The example below assumes you have a CRUD mixin that will add the model to the session and commit it when you call `save()`

```python
class Incident(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    reporting_user_id = db.Column(db.Integer,
                                  db.ForeignKey('user.id'),
                                  nullable=False)
    reporting_user = db.relationship('User', backref='incidents')

# IncidentSchema deleted for brevity

class IncidentFactory(factory.alchemy.SQLAlchemyModelFactory):
    class Meta:
        model = Incident
        sqlalchemy_session = db.session
    
    reporting_user_id = factory.LazyAttribute(lambda a: UserFactory().save().id)


```

**Comment by antgel** [comment]
@etiology Wow, firstly thanks for the helpful response. I'm new to sqlalchemy, and I'd missed your point (only need the foreign key). You opened my eyes to the idea of a CRUD mixin, and I've already refactored my code to use https://github.com/absent1706/sqlalchemy-mixins which will do lots of heavy lifting.

Then, I was left with the fact that I don't want to generate a `User` for every `Incident`, rather I want to relate generated `Incidents` to pre-existing `Users`. Eventually I realized that I don't (shouldn't?) add anything inside the `IncidentFactory` to handle this, rather that I can (should?) pass `User.id` in as a parameter, and that this usage is mentioned very early on in [the docs](https://factoryboy.readthedocs.io/en/latest/introduction.html):

> It is also possible to override the defined attributes by passing keyword arguments to the factory:

Something like this to create five `Users` and allocate each one one or two `Incidents`:
```
for _ in range(1, 5):
    user = UserFactory().save()
    db.session.add(user)
    for _ in range(random.randint(1, 2)):
        incident = IncidentFactory(reporting_user_id=user.id).save()
        db.session.add(incident)
```

So I'm closing this, as not only is it not a bug, but I've gone round the houses and learnt lots on the way. (But if what I'm doing now is some sort of anti-pattern, I'd appreciate being told. :))

**Comment by etiology** [comment]
@antgel Glad it was helpful.  Factory-Boy is an amazing tool and I find it to be full of cleverness.  Just the built in Faker lib support alone is very valuable.  Our C# devs were blown away by how cool this tool is python development.

One note about that CRUD mixin lib, I don't see any exception handling in the [save()](https://github.com/absent1706/sqlalchemy-mixins/blob/9e9ec50a01518421b5260327ad9013e245e3d83f/sqlalchemy_mixins/activerecord.py#L26-L32) method of that library so you will want to consider that.  Typically I would expect you would want to rollback a transaction if there is an error saving it, or perhaps add good logging so you know your app is having issues.
