### ISSUE TITLE
Duplicate key violates key constraint

### ISSUE THREAD

**Issue by jonathan-s** [FactoryBoy/factory_boy#568]
#### Description
I guess it's up in the air whether this is a bug or an improvement. Assume that you initiate a ModelFactory, it creates said model. The next statement you need that same model but with a specific ID. If that id already exists it will throw a duplicate key value violates unique constraint error. 

I would want it instead to get the original ID when initiating the factory.

**Comment by rbarrois** [comment]
Hi,

Not sure, what would you want it to do: replace the existing database instance with the newly defined value? Or return the existing database instance without changing anything?
i.e rather ``update_or_create`` or ``get_or_create``? In the second case, have a look at https://factoryboy.readthedocs.io/en/latest/orms.html#factory.django.DjangoOptions.django_get_or_create

**Comment by jonathan-s** [comment]
Thanks, I was looking for the second case and had missed that you could configure that! So I'll close this issue.
