### ISSUE TITLE
factory.build() saves instance to database

### ISSUE THREAD

**Issue by rjschave** [FactoryBoy/factory_boy#572]
#### Description
My understanding from the documentation (https://factoryboy.readthedocs.io/en/latest/index.html?highlight=build#using-factories) is that the build strategy will not save the instance to the database.

```WidgetFactory.build()``` does not save the instance to the database, but ```factory.build(WidgetFactory)``` does.

#### To Reproduce
Using Python 3.7.2, Django 2.1.7, faker 1.0.2, and factory-boy 2.11.1

##### Model / Factory code
```python
# models.py
from django.db import models

class Widget(models.Model):
    name = models.CharField(max_length=25)

# tests/factories.py
from factory import DjangoModelFactory, lazy_attribute
from faker import Faker
from ..models import Widget

faker = Faker()

class WidgetFactory(DjangoModelFactory):
    class Meta:
        model = Widget

    name = lazy_attribute(lambda x: faker.word())

```

##### The issue
Here are the steps to reproduce in the REPL:

```python
>>> import factory
>>> from widgets.tests.factories import WidgetFactory
>>> w1 = WidgetFactory.create()
>>> w1.pk
4
>>> w2 = WidgetFactory.build()
>>> w2.pk
# (w2.pk is None, as expected)
>>> w3 = factory.create(WidgetFactory)
>>> w3.pk
5
>>> w4 = factory.build(WidgetFactory)
>>> w4.pk
6 # (was not expecting the instance to be saved)
```

#### Notes
Perhaps I've misunderstood something here.  Should ```WidgetFactory.build()``` and ```factory.build(WidgetFactory)``` have the same behavior?

**Comment by rbarrois** [comment]
I think you've found a lack of examples in the docs ;)

The API of ``factory.build()`` is ``factory.build(model_class, factory_class=None, **kwargs)``: https://factoryboy.readthedocs.io/en/latest/reference.html#factory.build

Its intended use case is for quickly instantiating a class using factory_boy-provided helpers:
```python
user = factory.build(User, name=factory.Faker('name'), email=factory.Faker('email'))
```

Note how the first parameter is the **model class**:  ``factory.build(WidgetFactory)`` is strictly equivalent to:
```python
class _Factory(factory.Factory):
    class Meta:
         model = WidgetFactory
```

In order to build an instance of the factory, simply call ``WidgetFactory.build()``!

**Comment by matmarczak** [comment]
I try to understand the issue and improve docs but there is still something I am missing. 

In reference for module level functions descriptions for `build`, `create`,`stub` etc. are quite similar. The only difference is the word used for specifying return object. The same names are chosen for `Factory` methods. Correspondence of names suggests that module level functions return similar output as `Factory`.

**Comment by matmarczak** [comment]
Ok I understand the point. OP shouldn't use ModelFactory class as parameter to factory.build(). 

Isn't it misleading to permit creating Factory class with another Factory as Meta.model?
