### ISSUE TITLE
Recipe needed: how to handle ForeignKey to self model?

### ISSUE THREAD

**Issue by gotexis** [FactoryBoy/factory_boy#574]
Unfortunately, me cannot do a SubFactory to self model  yet. (hit recursion error)

**Comment by rbarrois** [comment]
You can perfectly; take a look at the [docs about circular references](https://factoryboy.readthedocs.io/en/latest/reference.html#subfactory-circular).

Don't forget to provide a way to **break** the recursive loop:

```python
# file: project/app/factories.py

class NodeFactory(factory.Factory):
    class Meta:
        model = models.Node

    parent = factory.SubFactory('project.app.factories.BaseNodeFactory')

# tests.py
def test_depth(self):
    root = NodeFactory(parent=None)
    grandchild = NodeFactory(parent__parent=root)
    self.assertEqual(root, grandchild.parent.parent)
```

However, I agree that this is not easy to find; would you have the time to add an example in the [recipes section of the docs](https://github.com/FactoryBoy/factory_boy/blob/master/docs/recipes.rst)?

**Comment by gotexis** [comment]
Hey, thanks for your tutorial. @rbarrois 

Just looking at it and a bit confused about why we where to put the test_depth() function in my code, but now I figured it must be that my use case is a bit different.

My main use (just 1 day into the project now) is to generate test data:
```python
UserFactory.build_batch(500)
UserFactory.create_batch(500)
```

I haven't touched test writing now, but I believe your solution applies to test cases?

As a workaround, here is what I am doing (using Django)
```python
parent =     User.objects.order_by('?')[0]     # I know this is quite inefficient
```

Thanks for making tutorials for noobs (just 6 month into programming) XD

**Comment by rbarrois** [comment]
The code works the same in a test or any batch feeding :)
Basically, you just have to tell the factory when to stop going higher in the hierarchy.

In your case, assuming the self ``ForeignKey`` is called ``invited_by``:

```python
# Create 500 users, each invited by a never-invited user
UserFactory.create_batch(500, invited_by__invited_by=None)
```

With that code, you'll get 500 users, each invited by a different user, and those inviting users haven't been invited.

Your example won't work as you expect: it selects a ``User`` object **only once**: when the module is imported.
A better solution for the same might be:
```python
class UserFactory(factory.django.DjangoModelFactory):
    parent_user = factory.fuzzy.FuzzyChoice(User.objects)
```

**Comment by gotexis** [comment]
Thank you kind sir.

I believe this these solutions will suffice for the current use case :))
