### ISSUE TITLE
Docs: Latest docs indicate that RelatedFactoryList is available, but feature is missing in latest release 2.11.1

### ISSUE THREAD

**Issue by kitanata** [FactoryBoy/factory_boy#589]
The documentation on readthedocs.io indicate that RelatedFactoryList is an available feature, however the latest release 2.11.1 (from May of 2018) does not actually have this feature.

This is confusing, because I would have expected the "latest" documentation in readthedocs to reference the "latest" release of the software, not what is available in the the master branch on github without a release pushed to PyPI. Version 2.11.1 documentation correctly shows that the RelatedFactoryList is not a feature of that version.

Please either push a new release to PyPI which matches the latest document on readthedocs.io or configure readthedocs.io to point the latest documentation to your latest release of the code available on PyPI and not to the master branch.

**Comment by federicobond** [comment]
Thanks for reporting this. @rbarrois should be pushing a release soon. We should have clarified the version at which `RelatedFactoryList` is introduced.

**Comment by dvf** [comment]
Bump

**Comment by Xzya** [comment]
Any update on this?

**Comment by foarsitter** [comment]
RelatedFactoryList is a nice addition!

**Comment by federicobond** [comment]
factory_boy 2.12.0 has just been released with this change. Thank you for your patience.
