### ISSUE TITLE
Misleading exception from changing get_or_create behaviour with #345

### ISSUE THREAD

**Issue by ulgens** [FactoryBoy/factory_boy#606]
#### Description
If any field given with `django_get_or_create` in a factory class, it's imposible to get the correct `IntegrityError` exception for duplicate-but-should-be-unique fields.

##### Model / Factory code
```python
class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User
        django_get_or_create = ('username',)

    username = 'test'
    email = 'test@example.com'

class User(models.Model):
    username = models.CharField(max_length=64)
    email = models.EmailField(unique=True)
```
#### To Reproduce
With given factory and model classes above, when i want to create an object with unique `username` but duplicate `email`:
* With release 2.11.1, i'm getting the normal-expected `IntegrityError` from Django.
* With release 2.12.0, i'm getting `ValueError` with presented with #345

It makes it impossible to write tests like this:

```python
class UserTestCase(TestCase):
    def test_duplicate_email(self):
        email = "cute@cats.xyz"

        UserFactory(username="test1", email=email)
        with self.assertRaises(IntegrityError):
            UserFactory(username="test2", email=email)
```

This is a bit similar case #598 but not the same. I don't think this a "something is not working" bug, but #345 introduces some unintended (and unnecessary imo) behaviour.

**Comment by mkokotovich** [comment]
I'm pretty sure #600 fixes the issue you're describing. Give it a try locally to see.

**Comment by francoisfreitag** [comment]
I understand the change in behavior and agree it’s confusing and not necessary. #345 shadows the real cause for the exception and causes information loss. I’m considering the best option to solve this and will report back in the days to come.
