### ISSUE TITLE
How to create fields for DjangoModelFactory dynamically? 

### ISSUE THREAD

**Issue by gandriyko** [FactoryBoy/factory_boy#628]
Is it possible to create fields for DjangoModelFactory in runtime?
For example for multi-language project.
```python
class DeliveryFactory(django.DjangoModelFactory):
    name_en = Faker('name')
    name_de = Faker('name')
    name_fr = Faker('name')
```
Something like processing settiings.LANGUAGES

**Comment by francoisfreitag** [comment]
Can you expand on your use case? For a multi-language project, I would expect a single `name` declared on the model and the application code would take care of the localization.

Perhaps https://github.com/FactoryBoy/factory_boy/issues/407 would help solve your issue?

**Comment by gandriyko** [comment]
There is [django-modeltranslation](https://github.com/deschler/django-modeltranslation) project.
It allows to declare models like:
```python 
models.py
class Product(models.Model):
    name = models.CharField()

settings.py
LANGUAGES = (
    ('en', 'English'),
    ('fr, 'French'),
    ('de', 'German')
)
```
and after migrations in database will be created table with fields
```
name_en
name_fr
name_de
```
Of course I can declare factory

 ```python
class ProducrFactory(django.DjangoModelFactory):
   name_en = factory.Faker('name')
   name_fr = factory.Faker('name')
   name_de = factory.Faker('name')
    class Meta:
        model = Product
```
but I want to do it automatically, depends on  LANGUAGES in settings.py
something like :
```python
class ProducrFactory(django.DjangoModelFactory):
    class Meta:
        model = Product
   def __ini__(self, ...):  # or __new__
       for l in settings.LANGUAGES:
          self._meta.post_declarations[l[0]] = factory.Faker('name')  # I don't know how
```

**Comment by francoisfreitag** [comment]
I see that `dajngo-modeltranslation` offers to pre-populate language fields to the same value as the one used in the default language.
https://django-modeltranslation.readthedocs.io/en/latest/installation.html#modeltranslation-auto-populate

Would that help?

**Comment by gandriyko** [comment]
No, it does not help
I want to generate post data to check my form validation:
```python
data = factory.build(dict, FACTORY_CLASS=ProducrFactory)
self.client.post(reverse('admin-product-created', data)
```
Problem is that in my form not contains field "name", only "name_en", "name_fr", "name_de".

**Comment by francoisfreitag** [comment]
Assuming the form is expected to contain `name_en`, `name_fr`, etc.

Perhaps you could use the lightweight declaration [`factory.make_factory`](https://factoryboy.readthedocs.io/en/latest/reference.html#factory.make_factory)?

```python
import factory


class Model:
    name_en = ""
    name_fr = ""

    def __init__(self, name_en, name_fr, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.name_en = name_en
        self.name_fr = name_fr


def make_declarations():
    # Could easily iterate over settings.LANGUAGES
    return {f"name_{lang}": factory.Faker("name") for lang in ["en", "fr"]}


ModelFactory = factory.make_factory(Model, **make_declarations())


if __name__ == "__main__":
    instance = ModelFactory()
    print(instance.name_en)
    print(instance.name_fr)
```

Prints:
```
Michelle Watson
Dwayne Reilly
```

**Comment by gandriyko** [comment]
Yep, this is what I need. Thank you!
