### ISSUE TITLE
Mutually dependent django model fields, with defaults

### ISSUE THREAD

**Issue by Joeboy** [FactoryBoy/factory_boy#635]
#### The problem
Suppose I have a model with two fields, which need to be set according to some relationship between them. Eg (contrived example) I have a product_type field and a size field. I'd like to be able to provide either, neither or both fields. If I provide eg. product_type, I'd like to be able to set the size field accordingly (eg. if product_type is "book", I'd like something like "299 pages". And if the size is provided as "299 pages", I'd like to be able to set the product type to something for which that is a valid size (ie. "book").

#### Proposed solution
What I've tried so far is having both fields as lazy_attributes, but I get a "Cyclic lazy attribute definition" error if I don't supply either of the dependent fields. I don't really have a proposed solution in terms of coding it, but I'd like my factory to be able to provide a default pair of field values if neither is provided by the factory caller (eg. product_type='shoes', size='42'). Or maybe there's a way of doing this already that I haven't found?

#### Extra notes
Just for context, I'm currently trying to replace a lot of django_any factories in a large django codebase, and there are a fair number of places where something like this would be very useful. Otherwise we have to write a bunch of things like "ProductGivenSizeFactory", which is much less convenient than having a single factory with the proper behaviour.

**Comment by federicobond** [comment]
My goto strategy when I have that problem is to just override the `_generate` classmethod (I don't think this is officially supported though).

```python
@classmethod
def _generate(cls, strategy, params):
    if 'product_type' in params and 'size' not in params:
        params['size'] = ...
    ... 
```

**Comment by Joeboy** [comment]
Thanks, that looks handy. Only thing is it's not ideal for foreign keyed things as you have to handle all the thing__otherthing__etc possibilities but it should work well enough, I think.
