### ISSUE TITLE
How to avoid Faker('domain_name') having the same domain twice in a row ?

### ISSUE THREAD

**Issue by stuaxo** [FactoryBoy/factory_boy#645]
I use factory.Faker("domain_name") in my factory, is there any way to stop it coming up with the same domain twice ?

I got a unique key error after calling my factory twice:
```
class SiteFactory(factory.DjangoModelFactory):
    class Meta:
        model = Site

    name = factory.Faker('word')
    domain = factory.Faker('domain_name')
```

```
        self.slovak_site = SiteFactory(id=5)
        self.czech_site = SiteFactory(id=6)
```

Got this unique key error one test run:
```DETAIL:  Key (domain)=(smith.info) already exists.```

**Comment by francoisfreitag** [comment]
The following test passes in my environment:

```python
class MyFakerFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.StandardModel

    foo = factory.Faker("domain_name")


class MyFakerTest(django_test.TestCase):
    def test_build_twice(self):
        self.assertNotEqual(
            MyFakerFactory().foo,
            MyFakerFactory().foo,
        )
```

Can you provide a minimal example where the same name is produced twice in a row?

**Comment by stuaxo** [comment]
The code was the same as this, but the error only happened after we had run a lot of times under CI.

I think it just randomly selected the same name twice.

I'll try running your above code in a loop and see what happens.

**Comment by francoisfreitag** [comment]
If you require a unique value, what about generating the domain name using a `factory.Sequence`? Faker randomly takes values out of a huge list (the companies). There’s a small chance the same value is taken twice in a row, and that’s expected.

**Comment by stuaxo** [comment]
Can I pass sequence to create_batch(...) as one of the parameters ?

I always assumed it wasn't possible, but it seems like a natural fit to me.


So I create sequence based on Faker("domain_name") somehow, and pull two items out of it that I use for each instance ?

**Comment by francoisfreitag** [comment]
Do you mean something like `MyFactory.create_batch(2, domain=["example.org", "example.com"])`? If so, then no, that is not possible.

What I meant by using `factory.Sequence` was:
```python
class MyFactory(factory.DjangoModelFactory):
    class Meta:
        model = AModel

    domain = factory.Sequence(lambda n: f"www{n}.example.org")
```
That yields unique values for domain as long as the sequence is not reset. That does not make domain names as realistic as Faker’s, but they should be good enough for tests and are sure to be unique.

---
An overkill way to generate unique domain from `Faker().domain_name()`:

```python
from faker import Faker


def generate_domain_name(n):
    """
    Returns a Faker generated domain with the sequence number
    appended to the first part of the domain.

    With n=6, jim.org becomes jim6.com.
    """
    base_domain = Faker().domain_name()
    parts = base_domain.split(".")
    first_part = parts[0]
    parts = [f"{first_part}{n}", *parts[1:]]
    return ".".join(parts)


class MyFactory(factory.DjangoModelFactory):
    class Meta:
        model = AModel

    domain = factory.Sequence(generate_domain_name)
```

**Comment by stuaxo** [comment]
Cheers, I'll close this now.

I think what I want is probably more a feature request for Faker.

domain_name (and others I'm sure), seem to be built from sequences.

It would be good if Faker could give you a way of getting a sequence from these kind of fakers.   Once that was in place, you factoryboy could give you interesting ways of working with them.

**Comment by stuaxo** [comment]
In the end I made a SiteFactory that handles this, posted below

It does feel like both faker and factoryboy would benefit from being able to handle uniqueness, especially when it comes to fields that are declared unique.

```python
# some code ommited
class SiteFactory(factory.DjangoModelFactory):
    class Meta:
        model = Site

    name = factory.Faker('word')
    domain = factory.Faker('domain_name')

    _used_domains = set()

    @classmethod
    def _get_unique_domain(cls):
        """
        Attempt to avoid already used domains.
        For speed, this doesn't check the database, so domains are only per-process.

        As we ran more tests, clashes of domain name occurred more often.
        """
        domain = cls.domain.generate()
        for i in range(8):
            if domain not in cls._used_domains:
                break
            domain = cls.domain.generate()
        return domain

    @receiver(post_delete, sender=Site)
    def _remove_domain_from_cache(sender, instance, created, **kwargs):
        """
        Remove domain from our used_domains cache
        """
        SiteFactory._used_domains.discard(instance.domain)

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        if "domain" not in kwargs:
            kwargs["domain"] = cls._get_unique_domain()
        cls._used_domains.add(kwargs["domain"])

        return super()._create(model_class, *args, **kwargs)
```
