### ISSUE TITLE
Different options for objects created by RelatedFactoryList

### ISSUE THREAD

**Issue by ibot3** [FactoryBoy/factory_boy#648]
It would be helpful if it would be possible to pass different options to the objects that will be created with `RelatedFactoryList`.

Example (a one-to-many relationship from `Foo` to `Bar`):
```
class FooFactory(BaseFactory):
    class Meta:
        model = Foo

    bar = None
    attr = 0

class BarFactory(BaseFactory):
    class Meta:
        model = Bar

    foos = RelatedFactoryList(FooFactory,
                              factory_related_name='bar',
                              size=2,
                              attr=(5, -5))

```
So that `BarFactory` creates two instances of `Foo`; One with `attr = 5` and one with `attr = -5`.

This is currently not possible or am I missing something?

**Comment by rbarrois** [comment]
Hi!

This should be possible with:

```python
class BarFactory(BaseFactory):
    class Meta:
        model = Bar
    foos = RelatedFactoryList(
        FooFactory,
        'bar',
        size=2,
        attr=factory.Iterator([5, -5]),
    )

**Comment by ibot3** [comment]
Yes, this is working, thank you!
