### ISSUE TITLE
RelatedFactory factory_related_name argument docs

### ISSUE THREAD

**Issue by psmolak** [FactoryBoy/factory_boy#685]
#### Description
Given https://factoryboy.readthedocs.io/en/2.12.0/reference.html#factory.RelatedFactory
the `name` parameter https://factoryboy.readthedocs.io/en/2.12.0/reference.html#factory.RelatedFactory.name shouldn't be called just like the positional parameter `factory_related_name`?

If that's not the case the documentation isn't clear for me about what the `name` argument is responsible for.

**Comment by francoisfreitag** [comment]
I think this is a documentation mistake, the `name` parameter should be named `factory_related_name`.
