### ISSUE TITLE
Generate Factory with extra non-model-fields (using Django)

### ISSUE THREAD

**Issue by estyxx** [FactoryBoy/factory_boy#691]
#### The problem
I need to have a Factory with some extra fields that are not in the model. I know that there is "exclude" but it's not useful for this particular problem.

I'm using Django Rest Framework, I have a Serializer who takes some extra-data that are not in the Model, only to call an external API, so I would like to have this extra-data generated by the factory ready to use, so I can use after in the test.

I know there is the `exclude` option but it's not the solution to this problem, because it removes the extra-attribute forever, they could be only useful if you have to generate others random-field (like it's explained [in the documentation](https://factoryboy.readthedocs.io/en/latest/reference.html#factory.FactoryOptions.exclude).

#### Proposed solution
The behaviour that I would like to have is, exclude them from the creation (because they aren't defined in the model), but after putting back these attributes as instance-attribute on the instance just created. 

So locally I customize my Factory to remove the extra-fields, create the instance e reput in the instance, but I would like to reuse this logic. 

Cloud be useful to integrate this behaviour in FactoryBoy directly (like another FactoryOptions)?
have you ever encountered a similar problem? Is there another way to solve it? 

I did something like: 

```

class MyModel(models.Model):
	title = models.CharField(_("title"), max_length=300)


@register
class MyModelFactory(DjangoModelFactory):value=1)
    title = factory.Faker("sentence", nb_words=4)

    # EXTRA-MODEL-FIELDS
    author = factory.Faker("name")

    class Meta:
        model = MyModel

    non_models_fields = (
        "author",
    )

    @classmethod
    def model_kwargs(cls, kwargs):
        # Exclude non-model field from creating the instance, but I need
        # some random values after to pass to the post API
        return {k: v for k, v in kwargs.items() if k not in cls.non_models_fields}

    @classmethod
    def fill_non_model_args(cls, instance, kwargs):
        for arg in cls.non_models_fields:
            if arg in kwargs:
                setattr(instance, arg, kwargs[arg])
            else:
                setattr(instance, arg, None)
        return instance

    @classmethod
    def _build(cls, model_class, *args, **kwargs):

        model_kwargs = cls.model_kwargs(kwargs)
        instance = model_class(*args, **model_kwargs)

        return cls.fill_non_model_args(instance, kwargs)

    @classmethod
    def _create(cls, model_class, *args, **kwargs):

        model_kwargs = cls.model_kwargs(kwargs)
        if cls._meta.django_get_or_create:
            return cls._get_or_create(model_class, *args, **model_kwargs)

        manager = cls._get_manager(model_class)
        instance = manager.create(*args, **model_kwargs)

        return cls.fill_non_model_args(instance, kwargs)
```

**Comment by francoisfreitag** [comment]
To add extra attributes to a model, I usually wrap the factory in a helper method. The factory creates the intended model, then remaining python attributes are set by the method.

Something like:

```python
def make_model_with_author(**kwargs):
    my_model = MyModelFactory.create(**kwargs)
    my_model.author = faker.Faker().name()
    return my_model
```

Since the extra fields are not part of the model definition, the factory provides no added value AFAICT?

Another option would be to define a [`post_generation`](https://factoryboy.readthedocs.io/en/latest/reference.html#post-generation-hooks) hook that adds attributes when its kwarg is passed to the factory.

**Comment by estyxx** [comment]
That is a nice recipe! Really, it was a little forced to put external attributes in the factory... 

Thank you!
