### ISSUE TITLE
Mentioning django-factory_boy Factories in the documentation

### ISSUE THREAD

**Issue by estyxx** [FactoryBoy/factory_boy#692]
#### The problem
There are some Django very common models (like User, Group, Permission) that should be nice to have their Factories ready to use in your test. And that does [django-factory_boy](https://github.com/FactoryBoy/django-factory_boy)! 
But I didn't find any reference in the documentation to it (maybe because is less maintained?), I discovered it because casually looked the repo here on GitHub... 

#### Proposed solution
Put some docs or reference to it in the docs? Maybe in the Django page...

**Comment by francoisfreitag** [comment]
That library does not look maintained: the last commit was 4 years ago and its test suite does not run. I don’t think the documentation should point to a stalled repository.

**Comment by estyxx** [comment]
It's a shame... It would be very useful... Do you know if it would be the chance to update it? Does it accept PR?? [I will make an issue on that repo maybe.. :) ]

**Comment by francoisfreitag** [comment]
I do not know. Based on issue https://github.com/FactoryBoy/django-factory_boy/issues/6 that has been unanswered for almost a year, it looks staled to me.
