### ISSUE TITLE
factory.Faker('uuid4') returns string, rather than UUID object (which, depending on project, returns Django ORM)

### ISSUE THREAD

**Issue by HoshiYamazaki** [FactoryBoy/factory_boy#694]
#### The problem
As title says.

#### Proposed solution
Provide solution (`uuid4-object` ?) to get away of that issue. I tried to generate `uuid` with `uuid.uuid4`, but it seems be not random, or convert `factory.Faker(uuid4)` using `uuid.UUID(str(factory.Faker(uuid4)))`, but this causes error in UUID library (`string badly formed` if I remember correctly).

**Comment by francoisfreitag** [comment]
Hi HoshiYamazaki,

Thanks for reporting the issue. `factory_boy` is [delegating the generation](https://github.com/francoisfreitag/factory_boy/blob/79161b0409842b5fc8a43d5844669f233403e14c/factory/faker.py) to the [faker](https://github.com/joke2k/faker) library.

```pycon
>>> import faker
>>> faker.Faker().uuid4()
'9eede68d-0eda-42ae-921e-46901fd6849c'
```

This proposal should be made to Faker.
