### ISSUE TITLE
Remove deprecated things before 3.x release

### ISSUE THREAD

**Issue by jeffwidman** [FactoryBoy/factory_boy#716]
The next release must be a major version bump because it [drops support for Python 2](https://github.com/FactoryBoy/factory_boy/pull/701).

@jdufresne noted in that PR:
> While working through the code, I noticed several comments of the form "Deprecated ... remove ...". So if there is a major version bump, it might be a good time to remove those as well.

We should *definitely do that*... will make our lives much simpler as it could be a long time til a 4.x release.

Here's the current list of deprecated things:
https://github.com/FactoryBoy/factory_boy/search?q=deprecated&unscoped_q=deprecated

Note that the Fuzzy stuff may be difficult to extricate w/o a lot of time, so may not make it in time for the `3.x` release... but the other stuff should be easy to remove.

cc @rbarrois @francoisfreitag @jdufresne

**Comment by francoisfreitag** [comment]
The remaining deprecations were added with release series 3.x.
