### ISSUE TITLE
Fixed Foreignkey is not working

### ISSUE THREAD

**Issue by nikolas310** [FactoryBoy/factory_boy#730]
Model is:
```
class School(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=100, unique=True)
    school= models.ForeignKey(School, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
```

ModelFactory is:

```
class SchoolFactory(factory.DjangoModelFactory):
    class Meta:
        model = School

class StudentFactory(factory.DjangoModelFactory):
    class Meta:
        model = Student
    name = factory.Faker('name')
    school= factory.SubFactory(SchoolFactory,
        name=factory.SelfAttribute('A School'))
```

Unique contrains failed. How to fix the issue

**Comment by russell310** [comment]
If you want to set a fixed foreignkey no need to add as subfactory. Just
```
class StudentFactory(factory.DjangoModelFactory):
    class Meta:
        model = Student
    name = factory.Faker('name')
    school= School.objects.get(name='A factory')
```

If you dont sure its created or not then

```
def get_school(name):
    school, created = School.objects.get_or_create(name=name)
    return school

class StudentFactory(factory.DjangoModelFactory):
    class Meta:
        model = Student
    name = factory.Faker('name')
    school= get_school('A School')
```

**Comment by pmav99** [comment]
@nikolas310 did you find the solution?

**Comment by nikolas310** [comment]
Yes.  Solution-
class StudentFactory(factory.DjangoModelFactory):
    class Meta:
        model = Student
    name = factory.Faker('name')
    school= School.objects.get(name='A School')

Now problem is:
If you dont have 'A School' it will raise error. So better solution-

def school_name():
    school, created = School.objects.get_or_create(name='A School')
    return school

class StudentFactory(factory.DjangoModelFactory):
    class Meta:
        model = Student
    name = factory.Faker('name')
    school= school_name()

**Comment by pmav99** [comment]
Thank you for answering.
