### ISSUE TITLE
factory.Sequence is not incremented sequentially.

### ISSUE THREAD

**Issue by ranelpadon** [FactoryBoy/factory_boy#735]
We're using version **2.8.1** for a long time and it's working smoothly, and decided recently to upgrade to latest version to make use of the improvements/fixes in random seeding/determinism in **2.11.0** at least.

But upon upgrading, we noticed that the `factory.Sequence` is behaving differently compared to the previous behavior.

Simplified model/factory class:
```python
class MyModel()
    value = models.IntegerField()

class MyFactory():
    value = factory.Sequence(lambda n: n)

    class Meta:
        model = MyModel
```

#### Output if the specific test method containing these lines is run:
```python
MyFactory().value  # 0
MyFactory().value  # 1
MyFactory().value  # 2
MyFactory().value  # 3
MyFactory().value  # 4
```
#### Output if the test method containing these lines is run as part of the suite:
```python
MyFactory().value  # 3
MyFactory().value  # 4
MyFactory().value  # 5
MyFactory().value  # 6
MyFactory().value  # 7
```

#### Output if the specific test method containing these lines is run:
```python
MyFactory().value  # 0
MyFactory().value  # 33
MyFactory().value  # 66
MyFactory().value  # 99
MyFactory().value  # 132
```

#### Output if the test method containing these lines is run as part of the suite:
```python
MyFactory().value  # 47
MyFactory().value  # 80
MyFactory().value  # 113
MyFactory().value  # 146
MyFactory().value  # 179
```

Hence, seems that the upgraded version increments by `33` instead of `1` for some reason. Are there code changes since **2.9.0** that could affect the sequencing? Note that there are no other setup/code changes except the `factory-boy` package's version. This is the same behavior even when just invoking the `MyFactory().value` manually and in succession in Django shell. Wondering also if other devs have similar observation since it seems easy to replicate. Thanks :)

**Comment by francoisfreitag** [comment]
I think there’s more to this issue than what has been reported.

I used the following script to test:
```python
import factory


class Foo:
    def __init__(self, value):
        self.value = value


class FooFactory(factory.Factory):
    value = factory.Sequence(lambda n: n)

    class Meta:
        model = Foo


if __name__ == "__main__":
    print(FooFactory.build().value)
    print(FooFactory.build().value)
    print(FooFactory.build().value)
    print(FooFactory.build().value)
```

Console output:

```
$ git checkout v2.8.1
HEAD is now at 110317e Release version 2.8.1
$ python test.py
0
1
2
3
$ git checkout v2.9.0
Previous HEAD position was 110317e Release version 2.8.1
HEAD is now at 5022bf6 Preparing release 2.9.0
$ python test.py
0
1
2
3
$ git checkout master
Previous HEAD position was 5022bf6 Preparing release 2.9.0
Switched to branch 'master'
$ python test.py
0
1
2
3
```

**Comment by ranelpadon** [comment]
@francoisfreitag Glad to hear if it's indeed only in our project and other devs are not affected. Will see also if I could replicate using the default Django installation. Thanks for your feedback. :)

**Comment by rbarrois** [comment]
From what I can read, this was a bug in your codebase; I'll close this issue, but please reopen it if you find out the bug was actually in factory_boy!
