### ISSUE TITLE
DjangoModelFactory creates primary key values as floating points

### ISSUE THREAD

**Issue by jtiai** [FactoryBoy/factory_boy#759]
#### Description

When using `DjangoModelFactory` primary keys (or AutoFields) are generated as floating points for some reason. Usually this doesn't matter since Django casts floating point (123.0 for example) to integer and it doesn't cause any issues.

We had unfortunate accident and tried to feed floating point as a string ('123.0') to primary key when it was sent as faulty JSON to REST API end point.

#### To Reproduce
*Share how the bug happened:*

##### Model / Factory code
```python
class MyModel(models.Model):
    pass

class MyModelFactory(DjangoModelFactory):
    class Meta:
        model = MyModel

```

##### The issue

```python
test_data = MyModelFactory.create()
print(test_data.id)
```
And for some reason`test_data.id` is a floating point number.

If model is created using plain Django value returned from database sequence is integer.

#### Notes

Behavior has been tested with latest version of factory-boy.

**Comment by rbarrois** [comment]
Hi!

Thanks for the report; it's very surprising.
Are you sure the issue occurs with the exact code you've shown? Can you compare it with a simple call to `MyModel.objects.create()`?

Which database backend are you using?

**Comment by jtiai** [comment]
Backend is Oracle. I can try to do more debugging to find out what causes the issue.

**Comment by jtiai** [comment]
This could be combination of very old Django and old factory-boy.
