### ISSUE TITLE
`make linkcheck` fails in CI

### ISSUE THREAD

**Issue by rbarrois** [FactoryBoy/factory_boy#771]
#### Description
Due to its default implementation, the `linkcheck` step of `make lint` triggers rate-limit protections on Github

#### To Reproduce
Run `make linkcheck`

**Comment by rbarrois** [comment]
@francoisfreitag Since you enabled `make linkcheck` in the first place, do you have some insight on this?

**Comment by francoisfreitag** [comment]
Thanks for the ping, I’ll look into moving the check to a [cron job](https://docs.travis-ci.com/user/cron-jobs/), to avoid running it often and hopefully avoid many requests and avoid the rate limiting.

**Comment by francoisfreitag** [comment]
Reporting back on this. Even limiting the number of workers with Sphinx is insufficient to circumvent the 429 Too Many Requests.

Related Sphinx issue https://github.com/sphinx-doc/sphinx/issues/7388.

**Comment by francoisfreitag** [comment]
This issue will be fixed on the next release of Sphinx (version 3.4). Can re-enable `linkcheck` then, possibly as a cron job instead of running for each PR.
