### ISSUE TITLE
ImageField inside Maybe declaration no longer working since 3.1.0

### ISSUE THREAD

**Issue by grondman** [FactoryBoy/factory_boy#796]
#### Description
In a factory that I defined for companies, I'm randomly generating a logo using a `Maybe` declaration. This used to work fine up to and including 3.0.1, but as of 3.1.0 it has different behaviour.

##### Model / Factory code
Leaving out the other fields as they cannot be relevant to the problem.
```python
from factory import Faker, Maybe
from factory.django import DjangoModelFactory, ImageField
from ..models import Company

class CompanyFactory(DjangoModelFactory):
    logo_add = Faker("pybool")
    logo = Maybe(
        "logo_add",
        yes_declaration=ImageField(width=500, height=200, color=Faker("color")),
        no_declaration=None,
    )

    class Meta:
        model = Company
        exclude = ("logo_add",)
```

##### The issue
Up to and including 3.0.1 the behaviour - which is the desired behaviour as far as I'm concerend - was that I could generate companies that either had a logo or did not (about 50/50 since I'm just using "pybool" for the decider field). If they had a logo, the logo would be 500x200 with a random color.

Now that I use 3.1.0, the randomness of about half the companies having logos still works, but _all_ generated logo's are now 100x100 and blue, which are simply defaults (although the [documentation](https://factoryboy.readthedocs.io/en/latest/orms.html?highlight=imagefield#factory.django.ImageField) says that "green" is actually the default), which is definitely something to fix :)

Perhaps I was misusing/misunderstanding this feature all along, but then I'd still like to know how to get the desired behaviour described.

**Comment by rbarrois** [comment]
This should now be fixed through #828 ; a new release should be available soon!
