### ISSUE TITLE
Round Robin strategy for FuzzyChoice

### ISSUE THREAD

**Issue by sne4ky** [FactoryBoy/factory_boy#802]
#### The problem
I need a round-robin strategy in the fuzzy.FuzzyChoices factory. Right now, there is no way to specify that I want to get at least every choice once

#### Proposed solution
Provide an attribute to FuzzyChoice(), that states the strategy.
For example:
`FuzzyChoice(["bear", "bull", "deer", "frog"], strategy="round_robin")`

Would yield the following:
```
>>> fc = FuzzyChoice(["bear", "bull", "deer", "frog"], strategy="round_robin")
>>> fc.fuzz()
'bear'
>>> fc.fuzz()
'bull'
>>> fc.fuzz()
'deer'
>>> fc.fuzz()
'frog'
>>> fc.fuzz()
'bear'
>>> fc.fuzz()
'bull'
```

#### Extra notes
This is interesting for generating fake init data and making sure every case appears

**Comment by rbarrois** [comment]
Hi! Thanks for the request; I believe this is already adressed by [`factory.Iterator`](https://factoryboy.readthedocs.io/en/latest/reference.html#factory.Iterator) ;)

If that's the case, I'd be interested to know how we can improve the docs so that this information is easier to find ;)

**Comment by rbarrois** [comment]
Closing this issue, which appears to be fixed. Feel free to reopen it if you're still hitting this!

**Comment by sne4ky** [comment]
Thanks a lot, that completely solves the issue
