### ISSUE TITLE
How does factory boy know of what type a field is?

### ISSUE THREAD

**Issue by mdczaplicki** [FactoryBoy/factory_boy#834]
I'm trying to make a tweak to factory boy so that it resolves properly pydantic models, but I'm not able to find a code responsible for getting the types for Django or SQLAlchemy models & generating proper values for these parameters.  
Where is the code that's responsible for this?

**Comment by rbarrois** [comment]
There isn't. Factory_boy will provide the values you've taught it to use :)
If a field should be an integer, provide an integer to the definition.

However, there is a planned (but not ready) feature to have factory_boy analyse a model class and generate declarations for it; at that stage, there will be a documentation for this mechanism and for hooks useful to make it compatible with various model frameworks.
