### ISSUE TITLE
How to use faker generator with Sequence field

### ISSUE THREAD

**Issue by Nihisil** [FactoryBoy/factory_boy#835]
I want to be able generate unique names like: "IBM.1", "Apple.2".

For version 2.12 this code worked fine:
```python
class CompanyFactory(BaseModelFactory):
    name = factory.Sequence(lambda n: f'{factory.Faker("company").generate()}.{n}')
    
    class Meta:
        model = Company
```

For version 3.1 I can't figure out how to write proper replacement of this code, because `.generate()` method can't be called anymore.

Is there any workaround for that?

LazyAttribute is not working, because I can't add random fields to the model: `TypeError: 'company_name_temp' is an invalid keyword argument for Company`

```python
class CompanyFactory(BaseModelFactory):
    company_name_temp = factory.Faker("company")
    name = factory.LazyAttributeSequence(lambda o, n: f"{o.company_name_temp}.{n}")
   
    class Meta:
        model = Company
```

**Comment by rbarrois** [comment]
When a parameter is only used within the factory, the simplest method is to simply use `class Params`:

```python
class CompanyFactory(BaseModelFactory):
    class Params:
         company_name_base = factory.Faker("company")

    name = factory.LazyAttributeSequence(lambda o, n: f"{o.company_name_base}.{n}")
   
    class Meta:
        model = Company
```

**Comment by Nihisil** [comment]
Thanks! it is working workaround.
