### ISSUE TITLE
build strategy is not working with reverse relations

### ISSUE THREAD

**Issue by ranelpadon** [FactoryBoy/factory_boy#856]
#### Description
We have interesting use case recently, and that is, to render a PDF preview without hitting the db. We realized that we could use the `build` strategy which creates instances, but not saving them in db.

##### Model / Factory code
```models.py

# models.py
class Order:
    ...

class Ticket:
    ticket = models.ForeignKey(Order, related_name='tickets')


# factories.py
class OrderFactory:

    @factory.post_generation
    def tickets(self, create, extracted, **kwargs):
        TicketFactory.build(order=self)
        print(self.tickets.all())  # returns []

class TicketFactory:
    ...
```

Observed behaviors:
```python
order = OrderFactory.build()
ticket = TicketFactory.build(order=order)
print(ticket.order)  # works ok
print(order.tickets.all())  # returns []
print(ticket.order.tickets.all())  # returns []

ticket = TicketFactory.build()
print(ticket.order)  # works ok
print(ticket.order.tickets.all())  # returns []
```

Expected behavior:
- `order.tickets` should be non-empty.

Is it working as intended? Is there a workaround so that the reverse relations will be linked properly? Removing the `post_generation` hook has no effect also. And they work as intended when using the default `create` strategy, so issue is only in `build` strategy. Thanks a lot.

**Comment by francoisfreitag** [comment]
That’s expected behavior. `order.tickets` is a related manager from Django, which looks up objects from relationships in the database. With the build strategy, objects are not stored in the database, so when the related manager looks for them in the DB, it finds nothing.
