### ISSUE TITLE
Improve post_generation Hook documentation

### ISSUE THREAD

**Issue by stephenfrench9** [FactoryBoy/factory_boy#882]
#### The problem
*Please describe the problem you're encountering (e.g "It's very complex to do [...]")*
The documentation does not describe the meaning or intended usage of the return statement in functions decorated Post-generation hooks.

For example, an example in the Docs is:

```
class UserFactory(factory.Factory):
    class Meta:
        model = User

    login = 'john'

    @factory.post_generation
    def mbox(obj, create, extracted, **kwargs):
        if not create:
            return
        path = extracted or os.path.join('/tmp/mbox/', obj.login)
        os.path.makedirs(path)
        return path
```

There is a return statement, but the effect of that return statement is not described. 

#### Proposed solution
*Please provide some wild idea you think could solve this issue. It's much easier to work from an existing suggestion :)*

Say for what the return statement is used. (or delete it? It seems like I can put anything in there and it doesn't affect what my hook does)

#### Extra notes
*Any notes you feel interesting to include: alternatives you've considered, reasons to include the change, anything!*

**Comment by francoisfreitag** [comment]
Thanks for the issue, I suggest removing the return value from post generation hooks in the documentation.

The only use for saving the results is private hook `_after_postgeneration()`, that allows factories to apply their custom logic based on the values returned by post generation hooks.

https://github.com/FactoryBoy/factory_boy/blob/9b256e48dd58ef7c97e3ddf09d972d1bb1d2df8e/factory/builder.py#L300-L309

An example use (and the only use in the library) is `DjangoModelFactory` inspecting the results and issuing a `save()` if a post generation hook ran. The goal is to keep the DB record sync’ed with the Python instance.

https://github.com/FactoryBoy/factory_boy/blob/9b256e48dd58ef7c97e3ddf09d972d1bb1d2df8e/factory/django.py#L168-L173

That use will be removed after the transition period for #316 is over. See the deprecation section of https://github.com/FactoryBoy/factory_boy/blob/master/docs/changelog.rst#330-unreleased for more details.

**Comment by stephenfrench9** [comment]
Ok this all makes good sense to me. 

Thank you for the quick action! and the summary as well.

I will eagerly await the change in the documentation!
