### ISSUE TITLE
unresolved reference `factory`

### ISSUE THREAD

**Issue by realsaeedhassani** [FactoryBoy/factory_boy#893]
#### Description
When I install `factory_boy`, python couldn't `import factory`

**Comment by rbarrois** [comment]
I can't reproduce this issue with a blank virtual environment.

Could you provide more details: which exact commands you're typing, what the resulting setup is?

Locally, I have no issue with running:
```sh
mkdir test-fboy
cd test-fboy
python -m venv venv
. ./venv/bin/activate
pip install factory_boy
python -c 'import factory; print(factory.__version__)'
```
