### ISSUE TITLE
What's about type-checking?

### ISSUE THREAD

**Issue by last-partizan** [FactoryBoy/factory_boy#898]
#### The problem

When using factory in the following way:

```
order = OrderFactory()
order.some_attr
```

Type-checker (pyright in my case) assumes that `order` is an instance of the `OrderFactory`, not `Order`.

When using `OrderFactory.create()` or `OrderFactory.build()`, result will be `Unknown` and at least type checked would not complain.

#### Proposed solution
Would be nice to have support for type annotations. Or, at least - define return type for `__init__` as `Any`, so type checker would not incorrectly assume wrong type.

**Comment by Kub-AT** [comment]
https://github.com/FactoryBoy/factory_boy/issues/468#issuecomment-759452373
