### ISSUE TITLE
SubFactory with a None value by default

### ISSUE THREAD

**Issue by aleehedl** [FactoryBoy/factory_boy#900]
#### The problem

Occasionally I want to have a SubFactory (or a RelatedFactory) whose value is set to None unless explicitly stated. That is, I would want to `FooFactory().bar` to be None but still be able to use `FooFactory(bar__name='test)` or `FooFactory(bar=BarFactory())`.

```
class BarFactory(DjangoModelFactory):
    name = factory.Faker("first_name")

class FooFactory(DjangoModelFactory):
    bar = factory.SubFactory(BarFactory)
```

Is this achievable somehow? Obviously I could use `FooFactory(bar=None)` but this is not ideal.

**Comment by rbarrois** [comment]
It's quite hard to support directly: in the current engine, declarations will be grouped by their "root", e.g all declarations starting with `bar__` are considered to be parameters for the `bar=` declaration.

If the default is `bar=None`, any value provided to `bar__name` would either cause a failure or be ignored.

The simplest option would be to use a `factory.Trait`:
```python
class FooFactory(factory.Factory):
  class Params:
    with_bar = factory.Trait(bar=factory.SubFactory(BarFactory))
```

With that, you could use:
```python
>>> FooFactory()  # Nothing requested
<Foo, bar=None>
>>> FooFactory(with_bar=True)  # Default call to `BarFactory`
<Foo, bar=<Bar, name="John">>
>>> FooFactory(with_bar=True, bar__name="test")  # Include `bar=`, and provide a value
<Foo, bar=<Bar, name="test">>
>>> FooFactory(bar__name="test")  # Slightly weird behaviour: the `BarFactory` is fully ignored.
<Foo, bar=None>

I hope this helps?

**Comment by aleehedl** [comment]
Thanks for the reply. Traits will have to suffice :-)
