### ISSUE TITLE
setup_next_sequence

### ISSUE THREAD

**Issue by cmflynn** [FactoryBoy/factory_boy#911]
#### The problem
What is the rationale for sequences starting at 0? Do any databases actually start with a zero based index?
```py
    @classmethod
    def _setup_next_sequence(cls):
        """Set up an initial sequence value for Sequence attributes.

        Returns:
            int: the first available ID to use for instances of this factory.
        """
        return 0
```

#### Proposed solution
    def _setup_next_sequence(cls):
        """Set up an initial sequence value for Sequence attributes.

        Returns:
            int: the first available ID to use for instances of this factory.
        """
        return 1

#### Extra notes
I caught this when testing some simple api code which is using the truthiness of a sequence value(probably a mistake but not my code xD). so: 
```py
#     id = factory.Sequence(lambda n: n)

if my_object.id:  # where this id comes from a factory boy model 
    ....
```

**Comment by rbarrois** [comment]
FactoryBoy can be used for any type of objects, not just database items; and indexes in an array start at `0` ;)

**Comment by rbarrois** [comment]
The best way to adjust that in your code would be to override the [`_setup_next_sequence` function](https://factoryboy.readthedocs.io/en/stable/reference.html#factory.Factory._setup_next_sequence) — it is a documented extension point, to allow for custom behaviour here!

**Comment by drobert** [comment]
>  and indexes in an array start at 0 ;)

I don't really follow this use case, though. If I wanted an arbitrary value from an array, I'd probably use Faker's `random_element` to select one rather than generating a sequence and using that to manipulate an array.
