### ISSUE TITLE
Consider renaming to FactoryPy or the like

### ISSUE THREAD

**Issue by scarroll32** [FactoryBoy/factory_boy#912]
#### The problem

There is massive gender imbalance in the tech industry and the Ruby library which this project was inspired from was renamed some time ago. A fixtures factory has nothing to do with a "boy".

[FactoryGirl was renamed FactoryBot](https://dev.to/ben/factorygirl-has-been-renamed-factorybot-cma)
- https://github.com/thoughtbot/factory_bot/issues/921
- https://thoughtbot.com/blog/factory_bot

#### Proposed solution

Rename the project to something gender-neutral, for example:

- FactoryPy
- FixtureFactory
- other?

#### Extra notes

Such a change will probably break lots of things, so it should be part of a major release bump. The GitHub organisation should also be renamed.

**Comment by AndreyGonchar** [comment]
In the linked [article](https://dev.to/ben/factorygirl-has-been-renamed-factorybot-cma) it is said
> Given the gender imbalance in the industry, anything named "girl" has the potential to cause alienation.
So as far as I understood, the library was renamed not for the sake of gender neutrality, but not to cause alienation.

**Comment by kingbuzzman** [comment]
> anything named "girl" has the potential to cause alienation

Personally I find this ridiculous; regardless of what something is called does nothing to influence me towards/away from it's usefulness. See the usefulness of a [hoe](https://castexrentals.com/images/thumbs/0025640_garden-tool-hoe-flat-tip_510.jpeg). 

I would still use this tool until I find a tool until I find a better tool for the job, the name means nothing more than a common/agreed upon variable we use to refer to it. I have no horse in this race, let me know how this goes.

**Comment by scarroll32** [comment]
I think that, as men, we should be finding positive ways to make IT feel safe and welcoming for women.

https://www.forbes.com/sites/carolinamilanesi/2021/06/29/the-importance-of-inclusive-language-and-design-in-tech/

Simple things such as using gender-neutral terms should not really be a big issue. 

> See the usefulness of a [hoe](https://castexrentals.com/images/thumbs/0025640_garden-tool-hoe-flat-tip_510.jpeg).

@kingbuzzman The fact that you have directly gone to a term that could be confused with a derogatory term for women is frankly sad and I encourage you to look at why you feel so threatened on this issue.

**Comment by scarroll32** [comment]
Closing this issue as the conversation is descending into flaming.

**Comment by kingbuzzman** [comment]
> I think that, as men, we should be finding positive ways to make IT feel safe and welcoming for women.

I'm all for this. We all have mothers, sisters, lovers(if you're so inclined as a male), etc..

> Simple things such as using gender-neutral terms should not really be a big issue.

I didn't say it was, if you remember I said:  _I would still use this tool until I find a tool that does a better job, the name is nothing more than a common/agreed upon variable we use to refer to it. **I have no horse in this race, let me know how this goes.**_

> @kingbuzzman The fact that you have immediately gone to a term that could be confused with a derogatory term for women is frankly sad, and I encourage you to look at why you feel so threatened on this issue.

I said I found it "ridiculous", and as such I came up an equally "ridiculous" name of a tool that "has the potential to cause alienation"; I was attempting to prove a point and you mistook it as "descending into flaming". See my other statement about not having a horse in the race.

I encourage you to take this discussion as what it is: a discussion, and reopen the issue. I've said my peace.

**Comment by incognos** [comment]
> I think that, as men, we should be finding positive ways to make IT feel safe and welcoming for women.
> 
> https://www.forbes.com/sites/carolinamilanesi/2021/06/29/the-importance-of-inclusive-language-and-design-in-tech/
> 
> Simple things such as using gender-neutral terms should not really be a big issue.
> 
> > See the usefulness of a [hoe](https://castexrentals.com/images/thumbs/0025640_garden-tool-hoe-flat-tip_510.jpeg).
> 
> @kingbuzzman The fact that you have immediately gone to a term that could be confused with a derogatory term for women is frankly sad, and I encourage you to look at why you feel so threatened on this issue.

@scarroll32 I think @kingbuzzman was making a point and not using a derogatory term. The meaning of words change constantly through the ages. This is hardly descending into flaming or insults.

**Comment by scarroll32** [comment]
> > I think that, as men, we should be finding positive ways to make IT feel safe and welcoming for women.
> > https://www.forbes.com/sites/carolinamilanesi/2021/06/29/the-importance-of-inclusive-language-and-design-in-tech/
> > Simple things such as using gender-neutral terms should not really be a big issue.
> > > See the usefulness of a [hoe](https://castexrentals.com/images/thumbs/0025640_garden-tool-hoe-flat-tip_510.jpeg).
> > 
> > 
> > @kingbuzzman The fact that you have immediately gone to a term that could be confused with a derogatory term for women is frankly sad, and I encourage you to look at why you feel so threatened on this issue.
> 
> @scarroll32 I think @kingbuzzman was making a point and not using a derogatory term. The meaning of words change constantly through the ages. This is hardly descending into flaming or insults.

"Ho" is not a derogatory term? https://english.stackexchange.com/questions/513653/is-ho-hoe-basically-an-equivalent-of-whore-which-differs-only-stylisticall

**Comment by incognos** [comment]
I believe he used the term "Hoe" which is a garden tool - https://www.merriam-webster.com/dictionary/hoe

**Comment by kingbuzzman** [comment]
> See the usefulness of a hoe

[Indeed I did](https://github.com/FactoryBoy/factory_boy/issues/912#issuecomment-1169772258).
