### ISSUE TITLE
Officially support Django 4.0, 4.1, 4.2 and Python 3.10, 3.11 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [FactoryBoy/factory_boy#914]
PyPi only lists support of `factory-boy` to Django <= 3.2 . I would like to see `factory-boy` officially supporting Django 4.0 on PyPi.

**Comment by rbarrois** [comment]
Good point, that's a short change on descriptors we missed when publishing version 3.2.2.
However, this would require a dedicated release to update the classifiers ;)

**Comment by francoisfreitag** [comment]
See https://github.com/FactoryBoy/factory_boy/commit/928fd2246c7d6d3c59463f3ce8b1f9f71a1f1ac7.

**Comment by GitRon** [comment]
Any update on the issue? 😅

**Comment by ThalusA** [comment]
What is preventing releasing v3.3.0 ? On the milestones it shows it's completed

**Comment by mhindery** [comment]
@francoisfreitag @rbarrois @jdufresne @jeffwidman tagging you since you are listed on  https://github.com/orgs/FactoryBoy/people, can somebody please release this version on Pypi? It's been several months at this point, and nothing needs to be done for it anymore except releasing.

**Comment by francoisfreitag** [comment]
Out of the people you’ve notified, only rbarrois has the permission to make a release (see the PyPI maintainers).
The release is blocked on https://github.com/FactoryBoy/factory_boy/issues/886, for which a solution has been proposed in https://github.com/FactoryBoy/factory_boy/pull/888 and needs a review.

**Comment by cclauss** [comment]
Please add 3.11 to the title of this issue.

**Comment by angvp** [comment]
What is the status of this? We've been using factory-boy on Django 4.0 and Django 3.10 w/o any issue, however I've found issues with Django 4.1 and 3.2.1 is there a new release planed? last release was in 2021 .. let the community knows how can we help, thanks

**Comment by tomhamiltonstubber** [comment]
Bump on this please, we'd be happy to help how we can!

**Comment by rbarrois** [comment]
That's (Finally!) done 🎉
