### ISSUE TITLE
Allow assignment with Django get or create.

### ISSUE THREAD

**Issue by nrbnlulu** [FactoryBoy/factory_boy#917]
#### The problem
*If a factory utilize `django_get_or_create` and the field set to None for some special case
the factory will return the same object no matter how many times you call it*

#### To Reproduce
```python

class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = 'myapp.User'  # Equivalent to ``model = myapp.models.User``
        django_get_or_create = ('username',)

    friend = factory.SubFactory(FriendFactory)
    
UserFactory.create_batch(5,
    friend = None
)
```
*

#### Proposed solution
*Allow assignment to django get or create*

### Note:
I know the docs warns about this.. 
![image](https://user-images.githubusercontent.com/88795475/161816474-025bf500-664a-4826-9a60-a183d3cff75d.png)

This is just annoying and makes you create duplicated factories.

**Comment by francoisfreitag** [comment]
`get_or_create` should not update the underlying model. Django `get_or_create` doesn’t, we don’t want to create a discrepancy there.
See #483 for more discussion.
