### ISSUE TITLE
DjangoModelFactory using another app model instead of the one it  supposed to use

### ISSUE THREAD

**Issue by avarajar** [FactoryBoy/factory_boy#918]
#### Description
*I have two models with the same name but under different apps. `music.Album and music_v2.album` so the issue is that when  `DjangoModelFactory` is trying to populate the data is using the wrong model*

##### Model / Factory code
```
class AlbumFactory(DjangoModelFactory):
    artist = SubFactory(ArtistFactory)
    name = Faker('catch_phrase')

    class Meta:
        model = 'music.Album'
```

#### Notes
It says this when is populating the data.. Is using `music_v2` model instead of `music`
<img width="263" alt="Screen Shot 2022-04-13 at 1 59 12 PM" src="https://user-images.githubusercontent.com/6046498/163255459-f608f015-f342-4da4-8593-22fc632d8573.png">

**Comment by francoisfreitag** [comment]
Did you have both apps installed in Django?
The logic to resolve the model asks the Django apps registry for the app and model name, so if they are registered correctly, FactoryBoy should be using the correct model.

If you find that it is not the case, please reopen, with some code to reproduce the issue.
