### ISSUE TITLE
factory-boy errors on Python3.7 without setuptools

### ISSUE THREAD

**Issue by matthewhughes934** [FactoryBoy/factory_boy#990]
#### Description

Importing `factory` without `setuptools` installed results in an
`ImportError` when trying to determine the distribution's version (only
on Python<3.8, above this it uses the builtin `importlib.metadata`):

    $ python --version
    Python 3.7.4
    $ python -m venv .venv
    $ source .venv/bin/activate
    $ pip uninstall --yes --quiet setuptools
    $ pip install --quiet factory-boy
    $ python -c 'import factory'
    Traceback (most recent call last):
      File "/tmp/tmp.qEc9M3LwV5/.venv/lib/python3.7/site-packages/factory/__init__.py", line 74, in <module>
        from importlib.metadata import version
    ModuleNotFoundError: No module named 'importlib.metadata'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/tmp.qEc9M3LwV5/.venv/lib/python3.7/site-packages/factory/__init__.py", line 78, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

#### To Reproduce

See above

##### Model / Factory code

N/A

##### The issue

N/A

#### Notes

Admittedly, it takes some effort to get a Python environment without `setuptools` (e.g. `venv` will install it) and the example above only works because there is a wheel we can install from. The original case was using `poetry` which wanted to remove anything but run-time requirements but took a bit more setup so I thought I'd share the simpler case above. I have a quick patch addressing this https://github.com/matthewhughes934/factory_boy/commit/995b319c0e6921861da7d1e862f1f7d4f0edd6e0

**Comment by kingbuzzman** [comment]
I would argue we should look forward and not backwards. There is a backwards compatible project from python to address this: https://github.com/python/importlib_metadata

By using this we can take a step forward.

**Comment by matthewhughes934** [comment]
> If importlib_metadata works for all Python versions, let's use that ;)

:+1: I think this is a fairly common solution to this problem, e.g. it's what [`pre-commit` does](https://github.com/pre-commit/pre-commit/blob/5c9e84410497a943ed3ad37fef3e2f9a72315bb8/pre_commit/constants.py#L5). Happy to get a patch up to use this for Python<3.8 if desired (i.e. basically the same approach as linked there)

**Comment by kingbuzzman** [comment]
![200](https://user-images.githubusercontent.com/329820/198704467-55e47c67-cced-43b7-b4a6-b7741cd90615.gif)
