### ISSUE TITLE
FuzzyInteger with low bound set does not work as intended

### ISSUE THREAD

**Issue by roryodonnell** [FactoryBoy/factory_boy#998]
#### Description
My intention is to have a randomized integer with a minimum value of 1 but instead the library returns a randomized integer between 0 and 1

#### To Reproduce
my_val = fuzzy.FuzzyInteger(low=1)

**Comment by francoisfreitag** [comment]
That’s because you need to provide a `high` bound.

```
my_val = fuzzy.FuzzyInteger(low=1, high=100)
```
